### ISSUE TITLE
Create TOC for README

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#100]
Would be useful to have, as otherwise people may find it hard to find the info they're after.

**Comment by sdruskat** [comment]
Probably should be done manually, as using tools like [github-markdown-toc](https://github.com/ekalinin/github-markdown-toc) smells like over-engineering for a TOC that isn't likely to change much.

**Comment by bast** [comment]
I have used the above and it's nice to initially create the TOC and from there on we can go manually for a while. The tool does not need to be introduced as dependency. Should I send a PR with a TOC?

**Comment by sdruskat** [comment]
Thanks @bast, that'd be great :)
