### ISSUE TITLE
Document how to deal with anonymous authors

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#106]
Somewhat related to #103.

We should discuss whether to introduce an enum to reflect non-retrievable and/or unknown authors, e.g. `UNKNOWN`, for when CFF files are auto-generated. This way, we can avoid introducing obfuscating pseudo-identities, which become interesting only when citation information is presented to human users of the software.

**Comment by sdruskat** [comment]
Countering what I said above in https://github.com/citation-file-format/citation-file-format/issues/106#issue-536420201, the "pseudo-identity" way of recording author information may be the more correct way after all. Concluding from a brief discussion I had with Dan Katz about this:

- `UNKNOWN` represents zero knowledge about the authors, which isn't true. We know that the authors have worked on the project that is represented.
- *The ... Project* or *The ... Team* represents the level of knowledge we have: not enough to list individual authors by name, but enough to know that they have worked on the project.

So to represent this level of knowledge, CFF files should include a placeholder author name, rather than an `UNKNOWN` enum.

Leaving this open for discussion, but I cannot see a scenario now, where **no** pseudo-identity can be constructed from the project/repository name. 

Automating this may lead to less nice-looking values such as `The https://github.com/user/project Team`, but this would still represent the knowledge we have.

**Comment by jspaaks** [comment]
From a technical POV I think this is covered by the aliases from https://github.com/citation-file-format/citation-file-format/pull/104.

Even the UNKNOWN option would be possible under https://github.com/citation-file-format/citation-file-format/pull/104, since the ``Person`` object no longer has any required fields.

 I'd be OK with closing this issue.

**Comment by sdruskat** [comment]
I agree with what you say, although `alias` doesn't seem to be the most obvious option. But we can document this possibility in the specs (and perhaps even in a FAQ-like bit on the website ("What to do when you don't know the authors?")).

How about closing this after it has been documented in the specs at least, @jspaaks?

**Comment by sdruskat** [comment]
Fixed in PR #272
