### ISSUE TITLE
HTML versions of specs on website are 404

### ISSUE THREAD

**Issue by ZedThree** [citation-file-format/citation-file-format#108]
The `HTML` links for the specifications here are dead:

https://citation-file-format.github.io/about/#/releases

**Comment by sdruskat** [comment]
Thanks for the heads up @ZedThree! I'll look into fixing this.

**Comment by sdruskat** [comment]
Resolved by simply removing the links to the HTML versions. I think this is okay because we want to encourage people to use the latest version rather than an old one, and the PDFs are available locally as well as on Zenodo for reference to older versions.
