### ISSUE TITLE
Read citation files with python

### ISSUE THREAD

**Issue by caseydm** [citation-file-format/citation-file-format#114]
Hello. I work on the [CiteAs](http://citeas.org/) project and want to improve our handling and parsing of CFF files. Right now we discover the CFF file and try to find a DOI, then use the DOI to build a citation. What I would love to do is parse the citation file directly and use that to build the citation.

Is there a python package available to do this kind of parsing?

**Comment by sdruskat** [comment]
Hi @caseydm, and thanks for your issue!

Great to hear that you want to improve the (already great) CiteAs to do this! It's exactly what CFF was built for :).

CFF is valid YAML, so you can read it generically with any Python YAML package (e.g., [ruamel.yaml](https://pypi.org/project/ruamel.yaml/)).

What may also be interesting for your use case is that we're in the process of building an object model for CFF in Python, which can be used to read CFF into objects and do some validation, but it'll be some time yet before this is available.

**Comment by sdruskat** [comment]
If you wanted the CFF information in another format that you are already parsing, you can also look into [cffconvert](https://github.com/citation-file-format/cff-converter-python), which can convert CFF to a number of formats.

**Comment by caseydm** [comment]
Yes I'm looking forward to implementing full support for CFF files! You're right that the object model sounds promising. I'll try out cffconvert, as we are working with bibtex quite a bit. So I can try and convert from CFF to bibtex. If that doesn't work I will give the YAML package a try. Thanks!

**Comment by jspaaks** [comment]
Hi @caseydm, sorry I'm late to the party. Let me know if you need help getting `cffconvert` to do what you want, I'd be happy for the feedback!
