### ISSUE TITLE
Ask contributors if they want to be authors for 1.2.0

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#116]
We've switched publication to Zenodo to be automated via the GitHub-Zenodo bridge, and use a GitHub Action that checks the metadata in `CITATION.cff` for equivalence with `.zenodo.json`. Therefore, it has become necessary to include all authors in [`CITATION.cff`](https://github.com/citation-file-format/citation-file-format/blob/main/CITATION.cff) so that they are added to the Zenodo publication.

We want to ask all
- contributors on the GitHub repository, and
- all people previously listed as contributors ("Other(s)") on [Zenodo](https://zenodo.org/record/3515946)

if they want to become authors of the Citation File Format as per the Zenodo publication.

I have written email regarding this to those of you for whom I had email addresses.
I'll also ping those of you for which I don't have any email addresses in a comment below.

## You want to be credited as an author of CFF?

To become an author of CFF, please add your details to the [`authors` section](https://github.com/citation-file-format/citation-file-format/blob/main/CITATION.cff#L4-L19) in this project's `CITATION.cff` as follows:

- [Start editing the file on GitHub](https://github.com/citation-file-format/citation-file-format/edit/main/CITATION.cff)
- Below the last author entry, please add your details  
(indentation is 2 spaces for the first line (starting with `-`), and 4 spaces for the rest of the lines):  
```
  - family-names: <Your "family names">
    given-names: <Your "given names">
    name-particle: <Any "name particles">
    name-suffix: <Any "name suffixes">
    orcid: https://orcid.org/<You ORCID iD>
    <any further person fields you want to use>
```
An overview of the details you can provide can be found in the [CFF documentation on `person` objects](https://github.com/citation-file-format/citation-file-format#person-objects).
- When you're done, please commit using the option to create a new branch for this commit and start a pull request.

Many thanks for your contributions to CFF! :pray: 

## You *don't* want to be credited as an author of CFF?

Please leave a brief comment here to let us know. And thanks for your contribution regardless! :pray:

**Comment by sdruskat** [comment]
Pinging @LourensVeen to please indicate whether or not you want to be credited as authors of the Citation File Format in future Zenodo publications? See https://github.com/citation-file-format/citation-file-format/issues/116#issue-890031540 :slightly_smiling_face:.

**Comment by sdruskat** [comment]
> Thanks for asking! I feel I haven't contributed significantly enough to be an author. Hopefully I will be contributor in future. And certainly I will be an advocate for this wonderful project.

Thanks @bast!

**Comment by rgaiacs** [comment]
@sdruskat Thanks for the email.  I feel I haven't contributed significantly enough to be an author.

**Comment by dpshelio** [comment]
@sdruskat it seems there's not the option to create a new branch anymore! GH creates a new one automatically (sad it didn't allow me to rename it before the PR is created).

**Comment by sdruskat** [comment]
> @sdruskat Thanks for the email. I feel I haven't contributed significantly enough to be an author.

Thanks, @rgaiacs, both for letting us know & for your contributions during the original discussion & with getting the word out!

**Comment by sdruskat** [comment]
> @sdruskat it seems there's not the option to create a new branch anymore! GH creates a new one automatically (sad it didn't allow me to rename it before the PR is created).

That's weird. I didn't know they did that now. Anyway, thanks, @dpshelio, for the PR, which is now merged.

**Comment by sdruskat** [comment]
Has been done and replies recorded/acted upon. Would like to hear back from @LourensVeen about this still, can you ping him at work somehow @jspaaks?

**Comment by jspaaks** [comment]
> Would like to hear back from @LourensVeen about this still, can you ping him at work somehow @jspaaks?

Good idea, he probably didnt notice our msg in the email storm

**Comment by LourensVeen** [comment]
Hi, sorry, this somehow got lost, twice. It looks like an email filtering rule I disabled some time ago somehow came back. Weird.

I had a bit of a look around, and I don't think any of my ideas in the end made it into CFF! That's fine of course, but I'd say that probably means I'm not an author even if I'm a contributor, if that makes sense :-).

**Comment by sdruskat** [comment]
@LourensVeen Thanks, it does make sense.

As everyone has reacted to this issue now, it can be closed.
Another issue should be opened to (re-)add those who didn't claim authorship to the "Other(s)" section for Zenodo in `.zenodo.json`.
