### ISSUE TITLE
Migrate from Travis to GH Actions

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#117]
Add pytest to test workflow.

**Comment by jspaaks** [comment]
PR #136

**Comment by jspaaks** [comment]
- .travis.yml was removed in PR
- webhook was disabled
- push trigger on travis.org was disabled

clsoing this issue

**Comment by alex-konovalov** [comment]
@sdruskat @jspaaks would like me to add a CI badge to the README file?

**Comment by jspaaks** [comment]
> @sdruskat @jspaaks would like me to add a CI badge to the README file?

Yes please!
