### ISSUE TITLE
ask Zenodo if merging two collections is possible

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#119]
we have one conceptdoi https://doi.org/10.5281/zenodo.1003149, and a newer one https://doi.org/10.5281/zenodo.4751536. The latter one is associated with this repository. It would be nice to have all CFF releases as versions in the same collection, ideally in the collection that we used to use (https://doi.org/10.5281/zenodo.1003149).

(Note: consider how future releases from this repo will be affected)

**Comment by sdruskat** [comment]
Asked today via contact form.

**Comment by jspaaks** [comment]
I've been developing https://github.com/jspaaks/zenodraft, which is supposed to help you draft (and publish) depositions on zenodo and zenodo sandbox. I think since you probably own the conceptdoi https://doi.org/10.5281/zenodo.1003149, we could try to make an access token for Zenodo, and then use the cli to create a new version of the current repo in the old conceptdoi collection (using only a subset of the files, like perhaps just the schema and the specs document README.md). It should be possible to just try it out without making anything final (as long as you don't do `zenodraft deposition publish <id>` that is)

See `zenodraft` usage example here: https://github.com/nlesc-calls/2021-test/blob/d31bbbccc8bdae200411d62536e854cc0f6e81fe/.github/workflows/publish.yml. We could opt out of the manual trigger and just use an on-release trigger that creates a prefilled draft on Zenodo for us to review and publish there by clicking the button if we like.

Fair warning: `zenodraft` is very much a no-guardrails prototype, feedback welcome.

**Comment by sdruskat** [comment]
Decide what should go on the schema release proper (on Zenodo):

### First thoughts

- schema_guide.md
- schema.json
- README
- PDFs?

**Comment by jspaaks** [comment]
My personal preference is to not use filenames with underscores but dashes, so `schema-guide.[md|pdf]`. Just esthetics I guess

**Comment by sdruskat** [comment]
> My personal preference is to not use filenames with underscores but dashes, so `schema-guide.[md|pdf]`. Just esthetics I guess

Agree:

Decide what should go on the schema release proper (on Zenodo):
### Second thoughts

    * schema-guide.md
    * schema.json
    * README
    * PDFs?

But also, this should go in its own issue, so: #219.

Closing this, as Zenodo have now set this up so that new releases from this repo will go under the old concept DOI https://doi.org/10.5281/zenodo.1003149.
