### ISSUE TITLE
simplify regex for validating urls

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#125]
(Spawned from https://github.com/citation-file-format/citation-file-format/pull/123/#discussion_r632421633)

Currently, the regex is https://github.com/citation-file-format/citation-file-format/blob/eb9d7f32f224d24cdf84ebd48415fa5fc693f9cd/schema-sandbox/schema.json#L117

which is difficult to read.

I would like to change it to `^(https|http|ftp|sftp)://` and combine it with `"format": "uri"` in the json schema. The two expressions will yield basically the same behavior (except for `sftp` which the simpler expression adds)

**Comment by sdruskat** [comment]
`"format": "uri"` isn't validated as such AFAIK, but I'd be happy to use `^(https|http|ftp|sftp)://` and move the definition of a more complex URI check to [a strict schema](#131).

**Comment by jspaaks** [comment]
Assigned @sdruskat because he opened a PR for this already.

**Comment by sdruskat** [comment]
#158 merged, closing.
