### ISSUE TITLE
Look into how to allow multi-licensed items

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#128]
Spawned from https://github.com/citation-file-format/citation-file-format/pull/124/files#r632449575

Look into how to allow multi-licensed items. Options are to change to using an array, or to use SPDX license expressions

**Comment by jspaaks** [comment]
Related discussion https://github.com/citation-file-format/citation-file-format/issues/105

**Comment by jspaaks** [comment]
Assigned @sdruskat because he opened a PR for this already.

**Comment by sdruskat** [comment]
#157 merged, closing.
