### ISSUE TITLE
simplify regex for isbn

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#130]
spawned from https://github.com/citation-file-format/citation-file-format/pull/124#discussion_r631920654

https://github.com/citation-file-format/citation-file-format/blob/main/schema.yaml#L435-L439

Currently matches:
```text
978-3-16-148410-0
ISBN: 978-3-16-148410-0
ISBN-10: 978-3-16-148410-0
ISBN-13: 978-3-16-148410-0
99921-58-10-7
9971-5-0210-0
960-425-059-0
80-902734-1-6
85-359-0277-5
1-84356-028-3
0-684-84328-5
0-8044-2957-X
0-85131-041-9
93-86954-21-4
0-943396-04-2
0-9752298-0-X
0-9752298-0-X
```

**Comment by sdruskat** [comment]
If we are going to introduce a lax and a strict schema (#131) this would be a great candidate for moving regex validation to the strict schema only.

**Comment by jspaaks** [comment]
For reference https://en.wikipedia.org/wiki/International_Standard_Book_Number.

If we decide to forgo the "ISBN: " bit, we could assume that there are at least 10 digits, at most 13 digits + at most 4 (dashes or spaces). Also, the last position might be an `X` check digit. So perhaps something like:

```
^[0-9X\- ]{10,17}$
```

or

```
^[0-9\- ]{10,17}X?$
```
?

**Comment by sdruskat** [comment]
I'd prefer this (the second) one for slightly higher precision:

> ```
> ^[0-9\- ]{10,17}X?$
> ```

**Comment by jspaaks** [comment]
PR was merged, closing
