### ISSUE TITLE
Create lax & strict schemas?

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#131]
Based on https://github.com/citation-file-format/citation-file-format/pull/123#discussion_r632392685:

Up until and including version 1.1.0, there have been a few very complicated regexes, and large enums in the schema.

I propose to introduce two versions of the schema, 

1. a **lax schema** (`schema.json`), i.e., one that mostly describes the **structure** of `CITATION.cff` files and does some very basic validation where useful.
2. a **strict schema** (`schema-strict.json`), i.e., one that not only describes the structure, but also imposes stricter criteria for valid **values**. This is the version that includes all complex regex and perhaps `enum`s for, e.g., licenses, etc.

Users for which performance is an issue can use the lax schema for validation, users for which correctness of instances is an issue can use the strict schema.

## List of fields for which stricter validation may be useful:

This list is up for discussion & suggestions for additions are welcome.

- [ ] `url`
- [ ] `isbn`
- [ ] `languages` (use correct ISO 639 enums)
- [ ] `identifier`:[`swh`](https://docs.softwareheritage.org/devel/swh-model/persistent-identifiers.html) (The [Wikidata entry](https://www.wikidata.org/wiki/Property:P6138) also provides a regex)

**Comment by sdruskat** [comment]
Look into whether it's possible to inherit/override schemas, as syncing 2 schemas for the same format would otherwise increase maintenance cost...

**Comment by sdruskat** [comment]
Think about use cases where 
- a strict schema would provide advantages over using the lax one, 
- the lax schema could use some more strictness

**Comment by sdruskat** [comment]
> Look into whether it's possible to inherit/override schemas, as syncing 2 schemas for the same format would otherwise increase maintenance cost...

Overriding doesn't seem to be supported natively, but can possibly be done via a combination of inheritance and the `allOf` keyword. I'll investigate.

**Comment by sdruskat** [comment]
So apparently, [OOP-like overriding doesn't work](https://json-schema.org/understanding-json-schema/reference/combining.html#id5), but I've pushed an example to the [lax-and-strict-schema branch](https://github.com/citation-file-format/citation-file-format/tree/lax-and-strict-schema) (as of https://github.com/citation-file-format/citation-file-format/commit/d0eb82e807cf9b4bd5d577442bac81dd83f6bb46) which shows one way of overriding values while keeping the two schemas fairly maintainable:

The root properties in `schema-strict.json` all point to the respective `$ref`s in the "lax" `schema.json`, while single properties can be selectively defined to implement stricter validation. As of https://github.com/citation-file-format/citation-file-format/commit/d0eb82e807cf9b4bd5d577442bac81dd83f6bb46, this is shown with the `doi` root property, which is overridden with a new pattrn starting with `doi:`.

We can use this mechanism to selectively override properties that we want to define stricter validation for.

**Comment by jspaaks** [comment]
My preference would be to only have the lax schema (most tools do not even implement all of that at the moment, see for example `references` not being handled by cffconvert). 

As to the stricter schema, i.e.
> one that not only describes the structure, but also imposes stricter criteria for valid values. This is the version that includes all complex regex and perhaps enums for, e.g., licenses, etc.

I think that schema validation will generally not be enough for applications that need more trust in the user input. For example, in the Research Software Directory, we (have to) resolve dois to see if they are conceptdois. This is not a solvable problem with schema validation.

Apart from the technical downsides, I also see a big downside in how we would have to communicate about the format if we have two schemas --this takes away from the simplicity that people seem to like.

**Comment by sdruskat** [comment]
After doing some exploration in JSON Schema, and considering the pros v the cons of having two schemas, I agree that there should only be one schema.
