### ISSUE TITLE
CFF file with special characters in yaml may cause trouble on Windows

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#137]
For example, this error here https://github.com/citation-file-format/citation-file-format/actions/runs/842415993 was "fixed" by changing the key-complete CITATION.cff file used for testing in this commit: https://github.com/citation-file-format/citation-file-format/pull/136/commits/b9453f359aa470fe5eda748e6feb9d561e8a6a69

**Comment by sdruskat** [comment]
Hm, is this a "bug" in cffconvert perhaps, and could it be fixed by reading with UTF-8 as supplied char encoding?

**Comment by jspaaks** [comment]
Sounds plausible, thanks for making the issue

**Comment by sdruskat** [comment]
Should be fixed in https://github.com/citation-file-format/cff-converter-python/pull/154.

**Comment by sdruskat** [comment]
Closing as this is being tracked in https://github.com/citation-file-format/cff-converter-python/pull/154.
Please re-open if the above doesn't fix this.
