### ISSUE TITLE
sort keys in the jsonschema alphabetically

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#148]
makes them easier to find, especially in longer lists

**Comment by sdruskat** [comment]
Suggest to do that in a separate PR once we're happy with the schema as such.

**Comment by jspaaks** [comment]
Agree. Or alternatively, if we find ourselves in a position where there arent any open PRs

**Comment by jspaaks** [comment]
When we're ready,

```shell
cat schema.json | jq -S --indent 4
```

**Comment by sdruskat** [comment]
@jspaaks As currently there are no open PRs that change `schema.json`, I'll fix this now.

**Comment by sdruskat** [comment]
Done in #218.

**Comment by jspaaks** [comment]
Took the liberty to assign you since the work was already done

**Comment by sdruskat** [comment]
Added and merged, closing.
For future changes to `schema.json`, it is the maintainers (our) responsibility to make sure the linting runs smoothly before merging PRs I guess.
