### ISSUE TITLE
expand entity in jsonschema schema

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#152]
https://github.com/citation-file-format/citation-file-format/blob/04ec97816b5f069c205885642027eb50a5a17135/schema.json#L668-L671

**Comment by sdruskat** [comment]
Also relates to #103.

**Comment by jspaaks** [comment]
Assigned @sdruskat because he opened a PR for this already.

**Comment by sdruskat** [comment]
#155 merged now, closing.
