### ISSUE TITLE
Suggestion for formulating the `message` entry

### ISSUE THREAD

**Issue by alex-konovalov** [citation-file-format/citation-file-format#161]
https://github.com/citation-file-format/citation-file-format/tree/1.2.0#message-required says:

### `message` (**required**)

`message` must specify instructions to users on how to cite the software the CITATION.cff file is associated with.

```yaml
message: "Please cite the following works when using this software."
```

- is there a recommendation that it should be a sentence finished with a dot `.` i.e., not a colon or no punctuation sign at all? Or this is an unnecessary complication, limiting flexibility, and missing dot could be added programmatically, when one uses the `CITATION.cff` file?

**Comment by jspaaks** [comment]
IMHO, let users do what they will with this, but we could give them a couple of examples that are formatted as sentences (#142).

```json
"examples": [
    "Please cite the following works when using this software.",
    "Please cite this software using these metadata.",
    "Please cite this software using the metadata from 'preferred-citation'.",
    "etc"
]
```

**Comment by jspaaks** [comment]
I added a few `examples` to the `message` key in PR #175.

**Comment by sdruskat** [comment]
I agree with @jspaaks to leave this to the user. Also see https://github.com/citation-file-format/citation-file-format/pull/175#discussion_r642340449.
