### ISSUE TITLE
Testing framework needs documentation

### ISSUE THREAD

**Issue by alex-konovalov** [citation-file-format/citation-file-format#165]
I've noticed #134 and observed that there is no description of how tests are organised (`CONTRIBUTING.md` would be an obvious place to tell contributors how they can run tests locally, if they wish), with a more detailed documentation in, say,  `test/README.md`. Is it described elsewhere, in the repository/wiki/issues? I could try to collect those pieces in `test/README.md`, or, if it's undocumented, try to write something from scratch, trying to understand how it is organised myself.

**Comment by jspaaks** [comment]
Hi Alexander,

the testing strategy is undocumented at the moment. The [testing workflow](https://github.com/citation-file-format/citation-file-format/blob/093f379498b7ea4f559bb3f0e54429a5b6f07277/.github/workflows/testing.yml) that you found already is probably the closest thing we have right now. In a nutshell, we use `pytest` to run the tests, which themselves are based on [`cffconvert`](https://pypi.org/project/cffconvert/)'s validation. `cffconvert` is currently able to test against version `1.0.3` and `1.1.0` of the schema, using [`pykwalify`](https://pypi.org/project/pykwalify/). We are planning to add validation of `1.2.0` to `cffconvert` in the not too distant future, so it would be fine with me to just ignore that part for now. In the process, we will also change the testing mechanism for `1.2.0` a bit, but that should not affect anything in this repo.

I like your idea of linking to `test/README.md` from CONTRIBUTING.md.

**Comment by alex-konovalov** [comment]
@jspaaks attempted in #167.

**Comment by alex-konovalov** [comment]
This did not close automatically - done in #167.

Next, I would like to see if there are any scenarios not covered by the tests. Of course, since there is no "code coverage" tool for the specification, it has to be done manually. Maybe trying to summarise that in some table. 

Alternatively, I could try to add new test cases as #134 suggests.



if there are any known

**Comment by alex-konovalov** [comment]
P.S. of course it was not closed automatically since the PR was made to `1.2.0` branch.
