### ISSUE TITLE
Overlap between root document and reference

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#168]
There is some overlap between 

1. the root document that describes a software or a dataset (in 1.2.0 at least)
2. a reference

I took inspiration from @LourensVeen's issue #103  in creating the table below to show what is shared.

| key name                | root document | `reference` (e.g. of type `software-code`) |
| :--                     | :-- | :--|
| abbreviation            |   | v |
| abstract                | v | v |
| authors                 | v | v |
| cff-version             | v |   |
| collection-doi          |   | v |
| collection-title        |   | v |
| collection-type         |   | v |
| commit                  | v | v |
| conference              |   | v |
| contact                 | v | v |
| copyright               |   | v |
| data-type               |   | v |
| database                |   | v |
| database-provider       |   | v |
| date-accessed           |   | v |
| date-downloaded         |   | v |
| date-published          |   | v |
| date-released           | v | v |
| department              |   | v |
| doi                     | v | v |
| edition                 |   | v |
| editors                 |   | v |
| editors-series          |   | v |
| end                     |   | v |
| entry                   |   | v |
| filename                |   | v |
| format                  |   | v |
| identifiers             | v | v |
| institution             |   | v |
| isbn                    |   | v |
| issn                    |   | v |
| issue                   |   | v |
| issue-date              |   | v |
| issue-title             |   | v |
| journal                 |   | v |
| keywords                | v | v |
| languages               |   | v |
| license                 | v | v |
| license-url             | v | v |
| loc-end                 |   | v |
| loc-start               |   | v |
| location                |   | v |
| medium                  |   | v |
| message                 | v |   |
| month                   |   | v |
| nihmsid                 |   | v |
| notes                   |   | v |
| number                  |   | v |
| number-volumes          |   | v |
| pages                   |   | v |
| patent-states           |   | v |
| pmcid                   |   | v |
| preferred-citation      | v |   |
| publisher               |   | v |
| recipients              |   | v |
| references              | v |   |
| repository              | v | v |
| repository-artifact     | v | v |
| repository-code         | v | v |
| scope                   |   | v |
| section                 |   | v |
| senders                 |   | v |
| start                   |   | v |
| status                  |   | v |
| thesis-type             |   | v |
| title                   | v | v |
| translators             |   | v |
| type                    | ? | ? |
| url                     | v | v |
| version                 | v | v |
| volume                  |   | v |
| volume-title            |   | v |
| year                    |   | v |
| year-original           |   | v |

I wonder if we should try to not repeat ourselves, for example with something along the lines of:

```json
{
    "additionalProperties": false,
    "properties": {
        "allOf": [
            "oneOf": [
                "$ref": "#/definitions/reference/data",
                "$ref": "#/definitions/reference/software"
            ],
            "message": {
                "type": "string"
            },
            "cff-version": {
                "type": "string"
            },
            "preferred-citation": {
                "oneOf": [
                    "$ref": "#/definitions/reference/data",
                    "$ref": "#/definitions/reference/software",
                    "$ref": "#/definitions/reference/other",
                ]
            },
            "references": {
                "items": {
                    "oneOf": [
                        "$ref": "#/definitions/reference/data",
                        "$ref": "#/definitions/reference/software",
                        "$ref": "#/definitions/reference/other",
                    ]
                },
                "minItems": 1,
                "type": "array",
                "uniqueItems": true
            }
        ],
    },
    "required": [
        "authors",
        "cff-version",
        "message",
        "title"
    ],
    "definitions": {
        "reference": {
            "data": {
                "$ref": "#/definitions/reference-properties/base",
                "type": {
                    "enum": ["data"]
                    "type": "string"
                }
            },
            "software": {
                "$ref": "#/definitions/reference-properties/base",
                "type": {
                    "enum": ["software"]
                    "type": "string"
                }
            },
            "other": {
                "$ref": "#/definitions/reference-properties/extended",
                "type": {
                    "enum": ["article", "art", "audiovisual", "etc."]
                    "type": "string"
                }
            }
        },
        "reference-properties": {
            "base": {
                "authors": {
                    "type": "object"
                },
                "commit": {
                    "type": "string"
                }
            },
            "extended": {
                "allOf": [
                    "$ref": "#/definitions/reference-properties/base",
                    "database-provider": {
                        "type": "string"
                    }
                ]
            }
        }
    }
}
```

**Comment by sdruskat** [comment]
See #164, I'm afraid combining schemas trying to use "real" inheritance doesn't work, as we cannot restrict properties anymore, or sensibly require different properties for different use cases.

**Comment by jspaaks** [comment]
Let's abandon this for now

**Comment by sdruskat** [comment]
Agree, closing.
