### ISSUE TITLE
To which branch to contribute?

### ISSUE THREAD

**Issue by alex-konovalov** [citation-file-format/citation-file-format#169]
Is there a long-term development model specifying this? I've understood from what others were doing that `1.2.0` is the branch for the new release, and I have to submit new PRs to that branch, but that was not obvious. It might be useful to indicate in `CONTRIBUTING.md` to which branch PRs should be submitted. `1.2.0` is quite far ahead of `main` and we don't want others to spend efforts on trying to fix things in `main`. I almost submitted a PR to delete `.travis.yml` myself before figuring out that that's already done in `1.2.0` branch.

What will happen with `1.2.0` branch when Version 1.2.0 is out - will it be merged into `main`?

**Comment by sdruskat** [comment]
Thanks @alex-konovalov, for this issue. Also cc-ing @jspaaks.

> Is there a long-term development model specifying this? 

No, or rather, not yet. I'd somewhat prefer something similar to [GitFlow](https://nvie.com/posts/a-successful-git-branching-model/), but this should be discussed.

> I've understood from what others were doing that `1.2.0` is the branch for the new release, and I have to submit new PRs to that branch, but that was not obvious. It might be useful to indicate in `CONTRIBUTING.md` to which branch PRs should be submitted. 

I'm sorry for this confusion. Yes, we should try to document this somehow. Perhaps in some sort of roadmap.

> What will happen with `1.2.0` branch when Version 1.2.0 is out - will it be merged into `main`?

Yes, `1.2.0` is basically a mixture of a release and a development branch. Perhaps we should actually rename it to `develop` and make it the default branch, what do you think @jspaaks? (We can always decide to use a separate release branch later on if we need or want).

**Comment by alex-konovalov** [comment]
Perhaps we don't need anything too complex... Something to think after 1.2.0 (I have an impression that you intend to release it before too long)?

**Comment by jspaaks** [comment]
To verify my understanding / clarify the difference between branching models:

1. **Git flow** branching model is where `main` branch only has stable releases and `develop` is the default branch and the target branch for merges from any feature branches.
1. **GitHub flow** branching model is where `main` is the default branch and the target of any feature branch. People who want stable releases should look at the `releases` page or perhaps Zenodo to find what they want.

In either case, issues are filed against the state of the default branch (which is not true at the moment; some of the more recent ones describe the code in `1.2.0` branch for example).

I have a slight preference for GitHub flow over Git flow, but it's not a dealbreaker for me. Either way, we should make sure that the branching reflects whatever model we choose, and mention our choice in `CONTRIBUTING.md` as @alex-konovalov suggested.

**Comment by alex-konovalov** [comment]
+1 for GitHub flow, to follow after 1.2.0 is out!

**Comment by sdruskat** [comment]
Yes, okay. I like GitFlow, but may be overengineering in this case, where we don't have lots of compiled artifacts, etc. Let's leave this open until `1.2.0` is out, then switch to GitHub Flow.

**Comment by sdruskat** [comment]
Related: #81
