### ISSUE TITLE
Re-release 1.1.0 on Zenodo

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#171]
After 1.1.0 had been released under a new concept DOI (coming from a different repository than past releases, i.e., this one instead of the .github.io one), we had asked Zenodo to comment on whether it's possible to re-bend the DOI graph to let 1.1.0 be a child of the old concept DOI.

They have deleted 1.1.0 as a form of reply.

Therefore, we have to re-release 1.1.0. I propose to do the following.

1. Re-release 1.1.0 under the *old* concept DOI (and change back any adaptions we've made):
    - [ ]  Zenodo badge
    - [ ] Text notification in 1.0.3-4 on Zenodo
2. Until 1.2.0 is ready for release, work with Zenodo to switch the repo that releases are picked up from .github.io to this one.

**Comment by jspaaks** [comment]
Couple of remarks, let's discuss later
1. Perhaps we should experiment with releasing on sandbox.zenodo first, see how things turn out. 
1. Also, we could attempt switching the repos. 
1. We could opt out of the Zenodo integration tool and use a GitHub Action instead, e.g to only upload the schema and/or the pdf, but not the config files.
 
gotta run!

**Comment by sdruskat** [comment]
I've rolled back the Zenodo links in 1.0.3-4 to the now non-existent 1.1.0, and the badge for the time being.

>     1. Perhaps we should experiment with releasing on sandbox.zenodo first, see how things turn out.

Yes.
 
>     2. Also, we could attempt switching the repos.

You mean bring the specs &c. back into `citation-file-format.github.io` repo? I wouldn't like that. Would prefer that we changed the source repository on Zenodo to this one (if this is possible).

>     3. We could opt out of the Zenodo integration tool and use a GitHub Action instead, e.g to only upload the schema and/or the pdf, but not the config files.

I don't think we have a PDF at the moment (could create one during CI if we think it's worth it via pandoc). Could be an option, although I like the integration (in theory).

I'll investigate whether it's possible to switch source repos...

**Comment by sdruskat** [comment]
@jspaaks Any opposition to re-releasing 1.1.0 manually under the old concept DOI now?

**Comment by jspaaks** [comment]
> @jspaaks Any opposition to re-releasing 1.1.0 manually under the old concept DOI now?

Nope, go right ahead

**Comment by sdruskat** [comment]
Done: https://doi.org/10.5281/zenodo.4813122
