### ISSUE TITLE
{"type": "dataset"} or {"type": "data"} ?

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#174]
Currently the 1.2.0 jsonschema says

```json
"type": {
    "enum": [
        "dataset",
        "software"
    ],
    "type": "string"
},
```

I think I prefer `data` over `dataset`

```
"type": {
    "enum": [
        "data",
        "software"
    ],
    "type": "string"
},
```

**Comment by sdruskat** [comment]
I'm not opposed to this, but would like to hear your reasons for preference @jspaaks :). Is it because `set` restricts to a single *thing* while the described object in a repo may be > 1? (In which case it could be a dataset of datasets.)

**Comment by sdruskat** [comment]
We decided on `dataset`, already implemented.
