### ISSUE TITLE
According to the docs, references should have a key 'term'

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#176]
but in the 1.2.0 jsonschema it doesnt

**Comment by sdruskat** [comment]
Neither does the YAML schema :smile:. Oh dear...

**Comment by jspaaks** [comment]
In principle, this could warrant releasing a bugfix version of past schemas, e.g. 1.0.4 in which we either delete the part of the documentation that claims one can have a `term`, or alternatively, adds `term` to the yaml schema. Is updating old schemas something we want to do, or do we simply deprecate them as newer versions of the schema come out? 

Related: #97

**Comment by jspaaks** [comment]
Looks like this was done https://github.com/citation-file-format/citation-file-format/blob/1f46e2b5c57fc30041582a83b725aed13feb3900/schema.json#L1591-L1595

**Comment by sdruskat** [comment]
> Looks like this was done
> 
> https://github.com/citation-file-format/citation-file-format/blob/1f46e2b5c57fc30041582a83b725aed13feb3900/schema.json#L1591-L1595

Yes indeed, closing :).
