### ISSUE TITLE
Add optional `description` to identifiers?

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#181]
Currently, `identifiers` takes `type` and `value`. It may make sense to add a third optional field `description` for human readers that describe what the identifier points to disambiguate for different use cases.

**Comment by jspaaks** [comment]
No objection

**Comment by sdruskat** [comment]
That's decided then, implementation to follow.

**Comment by sdruskat** [comment]
Merged into `1.2.0` with https://github.com/citation-file-format/citation-file-format/commit/1f46e2b5c57fc30041582a83b725aed13feb3900 :taco:
