### ISSUE TITLE
Abandon idea of YAtiML object model?

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#182]
Now that we've decided to go with a JSON Schema schema (which covers a lot of what we want to do already, although I think [proper object inheritance](https://json-schema.org/understanding-json-schema/reference/combining.html#subschemaindependence) would still be a nice-to-have), I'm wondering whether it still makes sense to pursue the idea of having an object model for constructing and validating CFF files at all.

To my mind, the use cases would have been:

- Validation against a well-constructed model
- The well-constructed model (also as a test case for model insufficiencies/less-than-optimal structures, e.g., #103)

Now I see a comparison between JSON Schema and YAtiML tilt things towards JSON Schema:

:heavy_plus_sign: Language-independent (JSON Schema validation libs available in a number of languages, YAtiML restricted to Python)
:heavy_plus_sign: Less cognitive overhead for users (having a schema is arguably more pervasive a concept than having an object model)
:heavy_minus_sign: JSON Schema is somewhat less optimized (inheritance not possible, i.e., duplication of some fields/structures is necessary).
:heavy_minus_sign: Validation output (error messages, warnings, etc.) can be somewhat controlled, reliance on output with JSON Schema libs.

All in all I think I'd opt for abandoning the YAtiML idea in favour of just using the JSON Schema. 
What are everyone's opinions (specifically @jspaaks, @LourensVeen (and perhaps @arfon))?

**Comment by LourensVeen** [comment]
That makes sense. For me an object model is definitely simpler than JSON Schema, but I suspect the average programmer these days would see it the other way around.

As for having both, we'd have to keep them in sync. Absent a tool that can generate Python classes from JSON Schema, that would have to be done by hand, and that's error-prone. One advantage YAtiML and an object model could have over dicts-and-lists is automatically filling out default values, but while there are many optional fields, I don't think there are many (any?) default values. The structure is also quite flat, so there are probably not many cases where you want to have `cff['x']['y']['z']` with all of them optional, and have to do
```
if 'x' in cff:
    if 'y' in cff['x']:
        if 'z' in cff['z']:
            # do something
```
Those would be the best arguments for YAtiML. I don't have the CFF spec swapped in at the moment, but I suspect they don't make it worth it to have a YAtiML version as well.

**Comment by jspaaks** [comment]
Good with me to abandon Yatiml and stick with Jsonschema for the time being.

**Comment by sdruskat** [comment]
FYI: There are exactly two default values (`message`, and `type`).
I think filling out defaults should be implemented by downstream tooling.

Also fine with me to stick with JSON Schema for the time being, hence closing this.
