### ISSUE TITLE
Add sensible defaults for selected fields

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#185]
As JSON Schema allows for [default values](https://json-schema.org/understanding-json-schema/reference/generic.html#id2), IMO at least two fields can use this: `type` and `message`:

- `type` - default: `software` (i.e., when `type` is missing or empty, `software` is assumed)
- `message` - default: `If you use this software, please cite it using the metadata from this file.` (i.e., to provide generators with a sensible default)

Note that both differ in what `default` semantically means wrt this section in the JSON Schema docs:

> The `default` keyword specifies a default value. This value is not used to fill in missing values during the validation process. Non-validation tools such as documentation generators or form generators may use this value to give hints to users about how to use a value. However, `default` is typically used to express that if a value is missing, then the value is semantically the same as if the value was present with the default value. The value of `default` should validate against the schema in which it resides, but that isn’t required.

**Comment by jspaaks** [comment]
PR was merged, closing
