### ISSUE TITLE
Publish schema to URL reflected in the `$schema` URI

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#190]
E.g., `"$schema": "https://citation-file-format.github.io/1.2.0/schema#"`

**Comment by sdruskat** [comment]
(Could be automated in a GH Actions release action.)

**Comment by sdruskat** [comment]
Done in PR https://github.com/citation-file-format/citation-file-format.github.io/pull/31.

**Comment by sdruskat** [comment]
`"$id"` should be `https://citation-file-format.github.io/1.2.0/schema.json#`!

This pattern works for the raw version in the branch, see image.

![image](https://user-images.githubusercontent.com/3007126/128368541-e72b4ff0-08ac-4302-999a-b2a5716a2d96.png)

**Comment by jspaaks** [comment]
Assigned @sdruskat because he created PR https://github.com/citation-file-format/citation-file-format.github.io/pull/31

**Comment by sdruskat** [comment]
Fixed in PR #302.
