### ISSUE TITLE
schema.json broken

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#198]
Argh, as of now, `schema.json` in `1.2.0` is broken, with duplicated keys and [broken JSON](https://github.com/citation-file-format/citation-file-format/blob/7e35d3b39bf73ffe020261f45e613589aa351960/schema.json#L1425-L1426).

Need to fix this now before anything else gets merged in.

**Comment by jspaaks** [comment]
could be that';s already fixed in PR #196

**Comment by sdruskat** [comment]
And now fixed in #200. Need to check in #196 at merge time whether the merge would re-duplicate keys.
