### ISSUE TITLE
Add non-author contributors . `.zenodo.json`

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#207]
Refs: #116.

We can add those contributors who didn't claim authorship to `.zenodo.json` so that they appear as contributors in the "Other(s)" section on Zenodo.

IMHO, this also strengthens the case for adding contributors to CFF at some point. This is also a [frequently requested feature](https://github.com/citation-file-format/citation-file-format/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Record+contributors%22), and I think will be in scope for CFF re citation metadata at some point in the future, when recording contributions and contribution types will become more widespread in the academic landscape.

**Comment by jspaaks** [comment]
Note: making changes to .zenodo.json will probably mean that the cffconvert github action will fail (it's finnicky), until we get to rework it at least. Maybe we should just disable it for the duration?

**Comment by jspaaks** [comment]
FWIW I made a .zenodo.json based on the metadata from the existing deposition. Somehow you can;t upload exactly the JSON metadata that you can get from Zenodo's frontend, it seems some properties are readonly or need to be renamed or something. In particular, I couldnt get the `related_identifiers` to work.

```json
{
    "access_right": "open",
    "contributors": [
        {
            "affiliation": "Software Heritage",
            "name": "Gruenpeter, Morane",
            "orcid": "0000-0002-9777-5560",
            "type": "Other"
        },
        {
            "affiliation": "Software Sustainability Institute, University of Manchester, UK",
            "name": "Silva, Raniere",
            "type": "Other"
        },
        {
            "affiliation": "University of Tromsø, Norway",
            "name": "Bast, Radovan",
            "type": "Other"
        },
        {
            "affiliation": "Octiog, Inc., USA",
            "name": "Crusoe, Michael R.",
            "orcid": "0000-0002-2961-9670",
            "type": "Other"
        }
    ],
    "creators": [
        {
            "affiliation": "Humboldt-Universitaet zu Berlin, Department of German Studies and Linguistics, Berlin, Germany",
            "name": "Druskat, Stephan",
            "orcid": "0000-0003-4925-7248"
        },
        {
            "affiliation": "Netherlands eScience Center",
            "name": "Spaaks, Jurriaan H.",
            "orcid": "0000-0002-7064-4069"
        },
        {
            "affiliation": "Software Sustainability Institute, University of Edinburgh, UK",
            "name": "Chue Hong, Neil",
            "orcid": "0000-0002-8876-7606"
        },
        {
            "affiliation": "ITS Research IT, University of Manchester",
            "name": "Haines, Robert",
            "orcid": "0000-0002-9538-7919"
        },
        {
            "affiliation": "University of Sussex, Sussex Humanities Lab",
            "name": "Baker, James",
            "orcid": "0000-0002-2682-6922"
        }
    ],
    "description": "<p><em>CITATION.cff</em> files are plain text files with human- and machine-readable citation information for software. Code developers can include them in their repositories to let others know how to correctly cite their software. This is the specification for the Citation File Format.</p>",
    "keywords": [
        "citation file format",
        "CFF",
        "citation files",
        "software citation",
        "format",
        "YAML",
        "software sustainability",
        "research software"
    ],
    "language": "eng",
    "license": {
        "id": "CC-BY-SA-4.0"
    },
    "publication_date": "2021-05-12",
    "references": [
        "A. M. Smith, D. S. Katz, K. E. Niemeyer, and FORCE11 Software Citation Working Group, \"Software citation principles,\" PeerJ Computer Science, vol. 2, p. e86, Sep. 2016 [Online]. Available: https://doi.org/10.7717/peerj-cs.86",
        "S. Druskat, \"Track 2 Lightning Talk: Should CITATION files be standardized?\" in Proceedings of the Workshop on Sustainable Software for Science: Practice and Experiences (WSSSPE5.1), 2017 [Online]. Available: https://doi.org/10.6084/m9.figshare.3827058",
        "R. Wilson, \"Encouraging citation of software - introducing CITATION files.\" 2013 [Online]. Available: https://www.software.ac.uk/blog/2013-09-02-encouraging-citation-software-introducing-citation-files",
        "O. Ben-Kiki, C. Evans, and I. döt Net, \"YAML Ain't Markup Language (YAML) Version 1.2. 3rd Edition, Patched at 2009-10-01.\" 2009 [Online]. Available: http://yaml.org/spec/1.2/spec.html",
        "J.-M. Hufflen, \"Names in bibtex and mlBibTeX,\" TUGboat, vol. 27, no. 2, pp. 243–253, Nov. 2006 [Online]. Available: https://www.tug.org/TUGboat/tb27-2/tb87hufflen.pdf"
    ],
    "title": "Citation File Format (CFF) - Specifications",
    "version": "1.1.0"
}
```

**Comment by brandonnodnarb** [comment]
> IMHO, this also strengthens the case for adding contributors to CFF at some point.

Yes, please. Adding a `contributors` key, which is essentially equivalent to the `author` key at a different contribution level, would fill a real gap.

**Comment by jankapunkt** [comment]
Looking at #246 this looks to be implemented, can I safely add a `contributors` section to my cff or will this lead to issues?

**Comment by jspaaks** [comment]
Hi @jankapunkt and welcome to the project! PR #246 added some metadata to the repository, using Zenodo metadata format so we can automatically make releases and have them show up on Zenodo with the right metadata. 

As a separate issue, adding support for `contributors` in CFF has also been discussed and the development branch (see https://github.com/citation-file-format/citation-file-format/pull/338) now includes it. I would recommend against using that branch for the moment though, as it is unreleased and subject to change. Our plan is to first finalize and release version 1.3.0 of the CFF schema, then update the tools such as `cffconvert` and `ruby-cff` (the tool that makes the GitHub widget work).

**Comment by jankapunkt** [comment]
@jspaaks thanks for the info, sounds promising

**Comment by jspaaks** [comment]
> We can add those contributors who didn't claim authorship to `.zenodo.json` so that they appear as contributors in the "Other(s)" section on Zenodo.

The original issue has been resolved, closing this.

PS the discussion on contributors and whether or not contributors should have roles continues e.g. here https://github.com/citation-file-format/citation-file-format/issues/112, including a question of my own https://github.com/citation-file-format/citation-file-format/issues/112#issuecomment-1725079361
