### ISSUE TITLE
Question: when validating CFF files, how will we validate that a licence is on the SPDX list?

### ISSUE THREAD

**Issue by hainesr** [citation-file-format/citation-file-format#208]
Seeing as I think a licence has to be SPDX per the standard, I suppose we need to validate that this is the case. Will it be possible to validate this via the JSONSchema validation route, or will we need to do this separately?

Apologies if this has been dealt with already.

**Comment by sdruskat** [comment]
Hi @hainesr, yes, this is covered by the JSON Schema schema. We are using an enum for this, which is compiled via https://github.com/citation-file-format/get-spdx-licenses: [schema.json lines 634ff.](https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema.json#L634-L638).

Feel free to close this issue if this answers your question :).
