### ISSUE TITLE
add examples of data citation to notes branch

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#217]
also, preferred-citation

**Comment by sdruskat** [comment]
> also, preferred-citation

I think this is superfluous, now that `1.2.0` is out? Or do you mean real-world examples, as in tracking actual uses f these features?

Feel free to close if this is something that needn't be addressed anymore @jspaaks.

**Comment by sdruskat** [comment]
FWIW, I'm currently looking into a corpus of CFF files to figure out how the format is used in the wild. `type` usage is one of the things I'm interested in.

**Comment by jspaaks** [comment]
`notes` branch has gone away, closing this issue
