### ISSUE TITLE
better regex for dates

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#223]
We currently use `"[0-9]{4}-[0-1]{1}[0-9]{1}-[0-3]{1}[0-9]{1}"` which enforces a leading 0 on the month and day, and doesnt include matchers for beginning and end of a string, which may make it possible to pass with a date like: `hello date 2000-01-01`

We could consider replacing with `"^[0-9]{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])$"` from https://stackoverflow.com/a/43347172.

**Comment by sdruskat** [comment]
By using `"format": "date"` We already "enforce" using the leading 0 format. And I think that that's good. The string pattern is a fallback for processing dates as plain strings and is (I think) in fact optional and should ideally (!) not be needed by JSON Schema libraries.

I agree that we should use string `^` and `$` though.

**Comment by sdruskat** [comment]
Another one for the 1.2.0 milestone...

**Comment by jspaaks** [comment]
Hello scope creep my old friend

**Comment by jspaaks** [comment]
BTW this is now invalid according to the schema (even though it passes our testing):

```yaml
date-released: 2020-01-01
```
I think we should allow for people writing dates like:
```yaml
date-released: "2020-1-1"
```
This is currently invalid.

What is valid though is:
```yaml
date-released: "2020-19-00"
```
Uh-oh.

**Comment by jspaaks** [comment]
Made PR #228, retained leading 0 on day and month, as this seems to be dictated by "format": "date".

**Comment by sdruskat** [comment]
Added, merged, and good. Now closing this issue.
