### ISSUE TITLE
add examples to license

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#224]
because it can be an element from enum or a multilicense with implict OR

**Comment by sdruskat** [comment]
Added to the milestone as well.

**Comment by sdruskat** [comment]
@jspaaks Hm, should the example for a license array be formatted as YAML (`"-Apache-2.0\n- MIT"`), or JSON (below)?
```
[
    "Apache-2.0",
    "MIT"
]

I think the former (YAML), but that obviously won't provide the actual literal string (includes `\n`).

**Comment by sdruskat** [comment]
Added in #229, which was merged. Closing.
