### ISSUE TITLE
Schema: regex missing escape?

### ISSUE THREAD

**Issue by hainesr** [citation-file-format/citation-file-format#235]
Hi @sdruskat, @jspaaks,

The Ruby regex parser doesn't really like this line, due to there being an unescaped `-`:

https://github.com/citation-file-format/citation-file-format/blob/684ed03b92331becb65c51326b8cbc38d72e6369/schema.json#L1264

If I load that line explicitly I get:

```ruby
rr = /^[0-9- ]{10,17}X?$/
(irb):1: warning: character class has '-' without escape: /^[0-9- ]{10,17}X?$/
```

So it's only a warning, but might be a pain and will be noisy in logs. Could we escape the `-`?

```ruby
rr = /^[0-9\- ]{10,17}X?$/
# no warning
```

I'm happy to fix this myself but wanted to check you were happy to.

Cheers...

**Comment by sdruskat** [comment]
Hi @hainesr, yes, please go ahead, thanks for catching this!

**Comment by jspaaks** [comment]
Was fixed and merged, closing this issue
