### ISSUE TITLE
CodeMeta converter

### ISSUE THREAD

**Issue by tmorrell** [citation-file-format/citation-file-format#236]
Just an FYI - We've put together a basic CodeMeta to CFF converter in GO (https://github.com/caltechlibrary/datatools) and  created a GitHub action to automate the conversion (https://github.com/marketplace/actions/codemeta2cff). It's not a complete mapping, but could be a good starting point for automated workflows.

**Comment by sdruskat** [comment]
Hi @tmorrell, and sorry for the late reply (due to holidays). Great news, this!

**Comment by sdruskat** [comment]
Both the Go API and the GitHub action are included in the [tools table in the README](https://github.com/citation-file-format/citation-file-format#tools-to-work-with-citationcff-files-wrench) now, closing this.
