### ISSUE TITLE
markdown link checker doesnt seem to check local targets correctly

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#243]
For example if there is a link

```markdown
### `license`

- type: (array of) [definitions.license-enum](#definitionslicense-enum.description).
- required: false
```
,
```shell
npm install markdown-link-check
node_modules/.bin/markdown-link-check --config .mlc-config.json schema-guide.md 
```

reports the link, but sees nothing wrong with it even though the target doesnt exist.

**Comment by sdruskat** [comment]
There seems to be work going on in a fork: https://github.com/tcort/markdown-link-check/issues/91

**Comment by sdruskat** [comment]
This seems to have been fixed (as witnessed in recent runs, i.e., [without errors](https://github.com/citation-file-format/citation-file-format/actions/runs/3059772317/jobs/4937536344), and [with only external errors (that shows details about internal links)](https://github.com/citation-file-format/citation-file-format/actions/runs/3059275607/jobs/4936462210#step:4:43).
