### ISSUE TITLE
1.1.0 license different on GitHub v Zenodo?

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#245]
Github

![image](https://user-images.githubusercontent.com/4558105/126894884-0c9bc3c7-826b-4619-aaea-f46448d64480.png)

Zenodo

![image](https://user-images.githubusercontent.com/4558105/126894866-be6efc84-280e-4c5e-a5a0-3a24093d0606.png)

**Comment by sdruskat** [comment]
Switched back to CC BY 4.0 on Zenodo.
