### ISSUE TITLE
Use bumpversion for managing version string across all files?

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#247]
There are now quite a few somewhat hidden places where we have version strings. Should we manage them using a dedicated tool like bumpversion (https://pypi.org/project/bump2version/)

For example: 

- https://github.com/zenodraft/zenodraft/blob/main/.bumpversion.cfg

**Comment by sdruskat** [comment]
Let's do it!

**Comment by jspaaks** [comment]
PR was merged, closing
