### ISSUE TITLE
Use standardized identifiers for licenses from SPDX instead of free text

### ISSUE THREAD

**Issue by mr-c** [citation-file-format/citation-file-format#25]
https://spdx.org/licenses/

**Comment by mr-c** [comment]
These identifiers are machine and human actionable.

For non-standard licenses the URL a fallback option should be retained, of course

**Comment by sdruskat** [comment]
Thanks @mr-c! I didn't know about SPDX, seems to make a lot of sense to use the short identifiers in CFF indeed!
