### ISSUE TITLE
Fix listing of `required` keyword in definitions

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#251]
Some sections for keys in the schema guide (e.g., `definitions.version`) currently have a `required` value, which is wrong (`version` should have one, and so should `definitions.reference.version`).

We need to check for each definition whether it has a `required` value set, and whether it should be there at all, and delete if unnecessary (as part of #240, and derived from the schema, i.e., for all definitions that *have* required keys, all subdefinitions should have the `required` keyword, but not the "root" definitions.)

**Comment by jspaaks** [comment]
How about removing `required`s from subkeys of `definitions` altogether?

**Comment by jspaaks** [comment]
the 1.2.0 branch currently has the following key descriptions with required: `true`

1. `authors`
2. `cff-version`
3. `message`
4. `title`
5. `definitions.entity.name`
6. `definitions.reference.author`
7. `definitions.reference.title`
8. `definitions.reference.type`

Everything else is required: `false`, so I guess that will at least result in correct behavior.

**Comment by jspaaks** [comment]
> and delete if unnecessary 

maybe setting
- **required**: N/A

more clearly communicates that we didn't simply forget it.

**Comment by sdruskat** [comment]
Yes:

**- required**: N/A

**Comment by sdruskat** [comment]
Closed in #273.
