### ISSUE TITLE
Should we validate all usage examples from the schema guide?

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#252]
Just thought that because at least I have written up some usage examples in the schema guide from the top of my head, we should perhaps construct a CFF file containing all examples from the schema guide to be validated during build?

This is
- a lot of work
- will include a lot of boilerplate (e.g., constructing whole CFFs just to test one line).

Still wanted to discuss this.

**Comment by jspaaks** [comment]
> I have written up some usage examples in the schema guide from the top of my head,

Same here

Ideally yes, we should test them. Potential problem is I typically use partial examples that only have the key that's being explained. Maybe a workaround could be: make a default cff, something like

```yaml
authors: 
  - name: test
title: test
cff-version: 1.2.0
message: test
```

then use some automation to extract all `yaml` snippets, parse the default file, overwrite with parsed snippet[i], then validate. Not airtight exactly, but could help safeguard against typos and such.

**Comment by sdruskat** [comment]
Probably the most promising route.

**Comment by sdruskat** [comment]
Done in PR #276 :tada:
