### ISSUE TITLE
Support software papers as a first-class entity

### ISSUE THREAD

**Issue by mdekstrand** [citation-file-format/citation-file-format#259]
The [principles paper](https://peerj.com/articles/cs-86/) that CFF seems to implement discusses software papers, but CFF at present seems to provide no way to designate a software paper and request that people cite it. I can put it in references and have a message of "please cite the CIKM paper", but that doesn't seem to designate it in a way that GitHub's citation widget might someday support (and right now the widget seems to completely ignore the message, but that's probably another piece of feedback for another place.).

**Comment by sdruskat** [comment]
Hi @mdekstrand, thanks for opening this issue!

The feature you are looking for is coming (:soon:) in version 1.2.0 with a `preferred-citation` field, which can take a `reference` object, e.g., a paper. This will be picked up by GitHub instead of the metadata for the actual software.

And yes, bringin the message into GitHub's UI is not something that we can do anything about, but is something to take note of for @arfon perhaps?

**Comment by mdekstrand** [comment]
Thank you, @sdruskat. This is excellent news! `preferred-citation` sounds like exactly what I would like to see.

In my field (information retrieval and recommender systems), software papers are a common practice, and there are an increasing number of venues that have created tracks specifically to promote the publication of software and dataset papers, such as the SIGIR Resource Track and the CIKM Resource Track. It will be great to have the citation file format better complement those initiatives.

**Comment by sdruskat** [comment]
Cool, good to hear that @mdekstrand! And yes, it's great to see that software papers are becoming more common. IMHO they're a great bridge between citing paper(s) and citing actual software, and will help getting from one to the other!

**Comment by arfon** [comment]
Thanks @mdekstrand! Note support for `preferred-citation` is coming in the next release of `ruby-cff` and will roll out on GitHub shortly afterwards (later this week I hope).
