### ISSUE TITLE
Contribute an official schema to the schema store project

### ISSUE THREAD

**Issue by jonasbb** [citation-file-format/citation-file-format#264]
The schema store project (<https://github.com/SchemaStore/schemastore>) contains a collection of JSON schemas for many JSON and YAML files. Since CFF files are also YAML files, it would be great if a schema could be added to that project. This way, many editors automatically pick up the schema and offer auto-completion and highlight errors.

**Comment by sdruskat** [comment]
Already in the works :slightly_smiling_face:, we're currently finalizing the docs for version 1.2.0 for which we switch to JSON Schema. The plan was to host on the CFF website (for `$id`) and also submit to schemastore.org.

**Comment by jspaaks** [comment]
> This way, many editors automatically pick up the schema and offer auto-completion and highlight errors.

Didn't know that, thanks

**Comment by sdruskat** [comment]
Depends on a fix for #190 (e.g., in PR #302).

**Comment by jspaaks** [comment]
BTW this is now part of Milestone 1.2.0, but I think this should happen after release of 1.2.0, hence should not be part of the milestone

**Comment by sdruskat** [comment]
This is done in PR https://github.com/SchemaStore/schemastore/pull/1788.

**Comment by sdruskat** [comment]
And merged into PR https://github.com/SchemaStore/schemastore/pull/1788 :tada:.
Thanks for initiating this, @jonasbb!
