### ISSUE TITLE
Authors with multiple affiliations

### ISSUE THREAD

**Issue by ghisvail** [citation-file-format/citation-file-format#268]
A question which may turn to a feature request : is there currently a way to specify authors with multiple affiliations?

Right now, it seems this attribute only accepts a `string`. Perhaps it would make sense to also allow a list of strings for this specific case?

**Comment by sdruskat** [comment]
Thanks, @ghisvail, for this feature request! You are right, while you *can* supply this information in a less structured way all in the one string, there's a good case for extending it to alternatively take, e.g., an array of `entity` objects, one for each affiliation.

We'll discuss this and may well implement it in a future version!

**Comment by bkhelifi** [comment]
Dear all,
I contact you to know if some discussions related to this topics have happened. For LTS releases, some contributors might have changed of affiliation, and thus a double affiliation scheme or having a 'past affiliation' might be interesting.
Is there any direction/idea/concept to implement this feature?
Thank you in advance!

**Comment by sdruskat** [comment]
Hi @bkhelifi, thanks for your comment. There hasn't been any further discussion on this yet, but allowing for multiple entities as affiliation still makes sense to me. I've added it to the respective version milestone.

I'm less sure about designating affiliations as 'past', but am happy to discuss semantics and implementation.

(Note I'll be on annual leave until late August from tomorrow, so may not reply during this time.)

**Comment by bkhelifi** [comment]
Thank you for your fast reply and your positive feedback for a next milestone.
'Past' is probably not wise... I was making a parallel to the authors list of papers for which some editors give the opportunity to precise a past/previous affiliation of some author. This use case will clearly happen for a software.
Thank you again

**Comment by jspaaks** [comment]
> Thanks, @ghisvail, for this feature request! You are right, while you _can_ supply this information in a less structured way all in the one string, there's a good case for extending it to alternatively take, e.g., an array of `entity` objects, one for each affiliation.
> 
> We'll discuss this and may well implement it in a future version!

Just a note for future consideration: In CFF [1.2.0](https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#definitionspersonaffiliation), `affiliation` is just a string, so the simplest extension that supports this would be to allow array of string (instead of array of entity object)

**Comment by maxnoe** [comment]
> I'm less sure about designating affiliations as 'past', but am happy to discuss semantics and implementation.

Affiliations usually have time ranges attached to them, so one could define `affiliations` as a list of objects with properties `name`, `from`, `until`, `address`, e.g. like this:

```
{
  ...,
  "affiliations": [
    {"name": "Affiliation 1", "from": "2016-01-01", "until": "2018-12-31"},
    {"name": "Affiliation 2", "from": "2019-01-01"},
  ]
```

Where a missing `until` means this is still valid.
This would also allow multiple affiliations (with overlapping periods).

**Comment by CaptainSifff** [comment]
My vote goes to the array solution of @jspaaks since it seems to be easily doable, and allows for features that are already present in other software as e.g. bibtex. The solution by @maxnoe is still certainly the more powerful one.

**Comment by cgobat** [comment]
Just adding another voice in support of this as something that would be nice to have.

**Comment by sdruskat** [comment]
After pondering this for a bit, I'm personally in favour of `affiliation` accepting a string as is, and additionally an array of `entity` objects, which have `date-start` and `date-end` to cover any needs in this direction. `entity` (or rather, `affiliation`) should have respective documentation.

(Note though that we have discussed the usefulness of adding past affiliations, and as `CITATION.cff` will always reflect a snapshot, past affiliations may not be relevant. However, they would be possible with `entity`.)
