### ISSUE TITLE
Create an issue template for people needing help with validation

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#291]
This could include:

- A polite notice saying this may take time on our side
    - Invite random readers to help with this issue if they can
- A link to the validation section in the README
- Add `help-wanted` and (to be created) `validation-issue` labels

Also add a bullet in the 10 mins. contrib section in README to say "IF you know how to validate, help someone out!" w/ link to label

**Comment by jspaaks** [comment]
BTW the default label for this is `help wanted` (without the dash), and I would prefer `validation` over `validation-issue`

**Comment by sdruskat** [comment]
Closed in PR #295
