### ISSUE TITLE
Add issue templates for tooling ideas and schema change ideas

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#292]
- This should be for schema changes only, so call it "propose a schema change" or similar. Outcome: `enhancement`
- Also create an issue template for tooling ideas. Outcome: label `tooling`

**Comment by sdruskat** [comment]
Done in PR #296. Close this when merged.

**Comment by jspaaks** [comment]
assigned @sdruskat because he made PR #296

**Comment by jspaaks** [comment]
PR was merged, closing the issue
