### ISSUE TITLE
Update `CITATION.cff` with `1.2.0` values at release

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#300]
Despite the version being bumped to `1.2.0` in PR #299, the rest of the metadata is still set at `1.1.0`.

**Comment by jspaaks** [comment]
specifically `date-released` and `doi`?

**Comment by sdruskat** [comment]
Yes. Fix is in PR #305.

**Comment by sdruskat** [comment]
Needs fix of version identifier before closing.

**Comment by sdruskat** [comment]
Added version DOI in https://github.com/citation-file-format/citation-file-format/commit/2ec9cdf278ef08498a6a8fd3f6b18dfd79bc7f39. Closing.
