### ISSUE TITLE
clean up branches

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#307]

**Comment by sdruskat** [comment]
Deleted the following 4:

- `278-define-identifier-alternative` (merged)
- `278-define-identifiers` (closed)
- `test-collapsible-sections` (not a working implementation)
- `lax-and-strict-schema` (disregarded setup)

Remaining for reasons:

- `test-encoding-test-bugfix` (may be needed for cffconvert encoding bug? Delete if not needed please @jspaaks)
- `notes` (implementation notes for GH feature)
- `gh-pages` (`index.html` should perhaps be kept for forwarding to new site? The rest can go I guess...)
