### ISSUE TITLE
Clarification about `zenodo.json` and `CITATION.cff`

### ISSUE THREAD

**Issue by epassaro** [citation-file-format/citation-file-format#312]
Hi! First of all I want to say thanks for this amazing tool. 

We're trying to use CFF in [our repository](https://github.com/tardis-sn/tardis) and seems this implies making big changes to our continuous delivery pipeline. My questions are:

1. According to README.md: _"When you publish your software on Zenodo via the GitHub-Zenodo integration, they will use the metadata from your CITATION.cff file"_. Does that mean that future changes to `zenodo.json` will be ignored by the Zenodo webhook after pushing `CITATION.cff` for the first time?
2. If that's true, is it safe to remove `zenodo.json`?

**Comment by epassaro** [comment]
Ok, seems my questions have been covered by this thread: https://twitter.com/ZENODO_ORG/status/1420357001490706442

**Comment by sdruskat** [comment]
> Ok, seems my questions have been covered by this thread: https://twitter.com/ZENODO_ORG/status/1420357001490706442

Hi @epassaro, thanks for opening the issue (and the kind words).

The Twitter thread explains some things indeed, perhaps it's good to briefly summarize here (e.g., for the benefit of future readers):

- The Citation File Format does not yet support all metadata fields that Zenodo uses.  
- If you publish on Zenodo and are concerned with the metadata needed purely for citation purposes (authors, version, etc.), you can _likely_ skip creating a `.zenodo.json` file altogether.  
- If you use metadata such as _contributors_, CFF may well be supporting them in future versions of the format. There is, for example, already a [milestone](https://github.com/citation-file-format/citation-file-format/milestone/8) tracking the much sought-after *record non-author contributors* feature. Once the metadata you use is available in CFF, you'll be able to skip creating a `.zenodo.json` file.  
In the meantime, you can use `CITATION.cff` as a basis for `.zenodo.json` and, e.g., use the [CFF converter](https://github.com/citation-file-format/cff-converter-python) to create one from the other, and the [cffconvert GitHub action](https://github.com/marketplace/actions/cffconvert) to track diverging information. This way, yuo only have to maintain/change the citation data in one place.
- If you use Zenodo-specific metadata such as _communities_, this isn't likely something that CFF will support, and so you will have to maintain `zenodo.json` (but can convert from `CITATION.cff`, see above).

Hope this is helpful. I'm closing this now as your concrete issue seems to have been solved. Thanks!
