### ISSUE TITLE
Make the validator script pip installable

### ISSUE THREAD

**Issue by renefritze** [citation-file-format/citation-file-format#314]
### Who needs the new tool?

Not a new tool, but everyone adding a CFF file to a python project could benefit from this. 

### What should the new tool enable users to do?

```
pip install cff-validator
cff-validator /my/project/directory
# Profit!
```
### What benefit would the new tool add?

Don't need to clone this repo, install dependencies manually and run from examples subdir.

### Implementation suggestions

Basically this would need a pypi project, setup.py with entry points for a script plus deps listing and maybe a GitAction to deploy new version on tags.

### Can you help?

- [x] Yes
- [ ] No

**Comment by sdruskat** [comment]
Hi @renefritze, and thanks for opening this issue.

Indeed, this would make it much easier to use! 

If you can help hands-on, please feel free to get started. We can, for example, integrate your repo in the CFF GitHub org as well. Otherwise, as this was on my agenda as well, I can ping you if I could find the time to get started on this.

**Comment by renefritze** [comment]
> If you can help hands-on, please feel free to get started.

I'd be happy to,  come second week of September (after pre-vacation crunch and actual vacation :smile: ).  


> We can, for example, integrate your repo in the CFF GitHub org as well. Otherwise, as this was on my agenda as well, I can ping you if I could find the time to get started on this.

So structurally you'd prefer if the script (w/ support modules etc.) moved to its own dedicated repo, right? 
If yes, then I'd suggest I start with a filtered history of this repo with only the related commits, then put the pip/GitHub actions infra on top. 

As for pypi project name. There's already a `cffconvert` so maybe name the new one `cffvalidate`?

**Comment by sdruskat** [comment]
@renefritze Great, thanks! Your help is much appreciated.

> I'd be happy to, come second week of September (after pre-vacation crunch and actual vacation smile ).

Perfect. Enjoy your vacation :palm_tree:!
 
> So structurally you'd prefer if the script (w/ support modules etc.) moved to its own dedicated repo, right?
> If yes, then I'd suggest I start with a filtered history of this repo with only the related commits, then put the pip/GitHub actions infra on top.

I think a separate repo would be the "cleanest" option, yes. I'll create one in the CFF org and invite you into the maintainer role, if that's okay?
 
> As for pypi project name. There's already a `cffconvert` so maybe name the new one `cffvalidate`?

`cffvalidate` is a good name I think :+1:.

**Comment by sdruskat** [comment]
Set up https://github.com/citation-file-format/cff-validator-python for this and invited René as maintainer.

**Comment by renefritze** [comment]
Excellent, thanks. I'll ping here once I got something to show.

**Comment by bielsnohr** [comment]
A question out of curiosity: is the desired functionality here not also provided by the [cffconvert python tool](https://github.com/citation-file-format/cff-converter-python)? More specifically `cffconvert --infile CITATION.cff --validate` should do what you are looking for. And `cffconvert` is already pip installable, which would satisfy your other criterion.

**Comment by sdruskat** [comment]
@bielsnohr Correct, in theory at least, because `cffconvert` isn't yet updated to use `1.2.0` as far as I know.

I think there is use in having a dedicated validation package that works on the schema directly. `cffconvert` could actually reuse that to bump validation to `1.2.0`. Pinging @jspaaks for his opinion, as he's the main developer of `cffconvert`.

**Comment by jspaaks** [comment]
My preference would be to have the validation as part of `cffconvert`, it just needs to be updated to include `jsonschema` based validation for 1.2.0.

At the moment, you can use `cffconvert` to validate and convert `CITATION.cff` files written in version 1.0.1, 1.0.2, 1.0.3 , 1.1.0, and I'm working to include 1.2.0. `cffconvert` is pip installable, is a command line tool, and will be avaiable Dockerized for those who don't want to fiddle with Python.

Validation is simply a matter of going to the directory where your `CITATION.cff` is, then `cffconvert --validate` does the trick.

**Comment by renefritze** [comment]
For me it really doesn't matter where the functionality lives, I just want to be able to `pip install something && something my.cff` and get a CI failure if I changed something incorrectly. 

AFAICT `cffconvert` does not yet allow to select which cff schema version to validate against. Is that planned? This could be important for projects I guess.

**Comment by sdruskat** [comment]
> AFAICT `cffconvert` does not yet allow to select which cff schema version to validate against. Is that planned? This could be important for projects I guess.

`cffconvert` branches validation depending on the value of `cff-version`. @jspaaks is currently working on support for `1.2.0`.

> For me it really doesn't matter where the functionality lives, I just want to be able to `pip install something && something my.cff` and get a CI failure if I changed something incorrectly.

I think `cffconvert` will meet these requirements, once `1.2.0` support is done? There's also the respective [GitHub Action](https://github.com/marketplace/actions/cffconvert) :slightly_smiling_face:.

**Comment by renefritze** [comment]
> `cffconvert` branches validation depending on the value of `cff-version`. @jspaaks is currently working on support for `1.2.0`.

Excellent.

> I think `cffconvert` will meet these requirements, once `1.2.0` support is done? There's also the respective [GitHub Action](https://github.com/marketplace/actions/cffconvert) .

That's even better/easier to use for us. So for me there's no need to split the validator script into that new repo any more. If you agree, we can just remove that again. And I'll just do nothing :wink:

**Comment by sdruskat** [comment]
> That's even better/easier to use for us. So for me there's no need to split the validator script into that new repo any more. If you agree, we can just remove that again. 

Agree :).l

> And I'll just do nothing 😉

Isn't that always the best outcome? 😄 

(I'll leave this open to be closed once the `cffconvert` supportin `1.2.0`is out.)

**Comment by AdityaSavara** [comment]
If I saw "cffconvert" I would not realize it validates. To me, having a separate repository for cffvalidate would be more intuitive.   More generally, I think the best would be to get this repository now before it is taken:
https://pypi.org/project/cff/

Then one can have "cff.validate" and "cff.convert" as modules within a larger package.  I would suggest to put cffvalidate inside "pip cff" and then later make it into a full package with both and other tools.

**Comment by sdruskat** [comment]
Created https://github.com/citation-file-format/cff-converter-python/issues/283 based on this last comment, but cffconvert has supported 1.2.0 for a good wee while now, and so I'm closing this issue :).
