### ISSUE TITLE
default message should be removed from schema

### ISSUE THREAD

**Issue by acli** [citation-file-format/citation-file-format#315]
The schema lists *message* as required, but it has a default value, which makes no sense because default values are useful only if the field is optional. If *message* being required is not an error, then its default value should be removed from the schema.

**Comment by sdruskat** [comment]
Thanks @acli for creating this issue!

I agree with you generally, but we also use JSON Schema to suit the needs of downstream clients, e.g., an initializer website that is currently under construction. And while for strict uses of the schema file I agree that this wouldn't make sense, I think that it does make sense in this (and some other) context, where the value is required (which is correct, by the way), but we also provide a default value as pre-fill information, or as suggestion to the user.

What do you think?

Let me also bring @jspaaks into the conversation to get his opinion, but I'm leaning towards making this a <kbd>wontfix</kbd>, as I cannot predict this breaking anything (other than the strict logic).

**Comment by jspaaks** [comment]
Agree with @sdruskat on this one. Having a `default` doesn't break anything, and may help downstream tools, for example when populating a dropdown list with examples (from `examples`) and preselecting a default (from `default`).

For reference: http://json-schema.org/understanding-json-schema/reference/generic.html#annotations

**Comment by sdruskat** [comment]
Thanks @jspaaks.

@acli Closing this as <kbd>wontfix</kbd>. Please re-open if you disagree.
