### ISSUE TITLE
Incorrect regexp for isbn

### ISSUE THREAD

**Issue by acli** [citation-file-format/citation-file-format#323]
According to the current schema.json, the pattern for isbn is

    ^[0-9\\- ]{10,17}X?$

This is incorrect. An X, if it occurs, is the check digit and part of the ISBN and I believe only possible for 10-digit ISBN’s. Since hyphens are optional, it is possible to encounter an ISBN that matches ^[0-9]{9}X$ but not the above pattern.

I believe a more accurate pattern would be

    ^(([0-9][- ]?){9}[0-9X]|([0-9][- ]?){12}[0-9])$

**Comment by acli** [comment]
Test case: 052145848X (Old English : A historical linguistic companion / Roger Lass)

**Comment by acli** [comment]
I’m not sure if it’s necessary to cap allowed values to 17 characters. If this is necessary/desirable and if we can rely on the existence of the (?=) (positive lookahead) operator, the regexp

   ^((?=.{10,13}$)([0-9][- ]?){9}[0-9X]|(?=.{13,17}$)([0-9][- ]?){12}[0-9])$

should ensure that 10-digit ISBN’s can have a maximum of 3 hyphens and 13-digit ISBN’s canm have a maximum of 4 hyphens.

**Comment by sdruskat** [comment]
Thanks for flagging this! I've now read up again on ISBNs and understand that `X` is actually a representation of `10` in the checksum.

With version 1.2.0, we have consciously simplified or dropped many regexes to avoid the maintenance and cognitive overhead for people using the schema in downstream tools. Therefore, I'm shying away a bit to adopt the last regex, especially because it relies on positive lookahead. The first option you propose looks much better IMHO.

Do you want to put up a pull request, or should we fix this ourselves?

**Comment by acli** [comment]
I can put up a pull request, but it will take a bit of time, since I just cloned the repo; I didn’t fork it

**Comment by sdruskat** [comment]
> I can put up a pull request, but it will take a bit of time, since I just cloned the repo; I didn’t fork it

Great, thanks! Please also add yourself to the `CITATION.cff` file as you see fit!

**Comment by acli** [comment]
I’m a little lost with the instruction about updating CHANGLOG.md. Do I add the change above “1.2.0”, or would someone else update the change log?

**Comment by acli** [comment]
Sorry, I haven’t done this for so long I forgot to use a branch. Let me delete my fork and try again.

**Comment by sdruskat** [comment]
> I’m a little lost with the instruction about updating CHANGLOG.md. Do I add the change above “1.2.0”, or would someone else update the change log?

@acli The change goes under the `## [Unreleased]` section, in a (new) subsection (we use the [keepachangelog subsections](https://keepachangelog.com/en/1.0.0/#how). In the case of the regex fix, this would be `### Fixed` :slightly_smiling_face:.

> Sorry, I haven’t done this for so long I forgot to use a branch. Let me delete my fork and try again.

Absolutely no problem, we're grateful for your contribution! Let me know if I can help with anything.

**Comment by acli** [comment]
@sdruskat Question: Where do I put my name in CITATION.cff? Do I put it under authors? But if I put it under authors wouldn’t that mess up citations for v1.2.0?

**Comment by sdruskat** [comment]
> @sdruskat Question: Where do I put my name in CITATION.cff? Do I put it under authors? But if I put it under authors wouldn’t that mess up citations for v1.2.0?

@acli Yes, the `authors` section would be the right place. I don't think this would mess with the citations for CFF as long as we don't merge into `main` without changing the version information in the CFF file (which is something we will do during review).

We still need to optimize the development workflow a bit, but I think it probably makes sense to divert the PR to a non-default branch during review. We still need to decide whether this would be its own hotfix release (1.2.1) or wait until we have the next feature release ready (1.3.0).

@jspaaks, thinking about this, perhaps we should adopt something more akin to GitFlow after all, at least having a `develop` branch would make sense here I think in terms of versioning and citations? (Would need to set the version to `1.3.0-SNAPSHOT` or similar.)

**Comment by jspaaks** [comment]
Agreed, it looks like I made a mistake when writing the regex. How about we use at least 9, not 10, chars from the set, like so
```
^[0-9\\- ]{9,17}X?$
```

> @jspaaks, thinking about this, perhaps we should adopt something more akin to GitFlow after all, at least having a develop branch would make sense here I think in terms of versioning and citations? (Would need to set the version to 1.3.0-SNAPSHOT or similar.)

Spawned new issue #324

**Comment by acli** [comment]
BTW, the usual way to include a hyphen in a regex is to front the hyphen:

    ^[-0-9 ]{9,17}X?$

This way we avoid escaping the hyphen. But I really have issue with this regex because I know (to the best of my knowledge) a terminal X is impossible in ISBN13 (because EAN does not allow X as a digit); that being said, I’d still rather you wrote

    ^[-0-9 ]{9,16}[0-9X]$

but even if it were written this way anyone who knows how ISBN’s work will have an issue with it. I was only trained as a library volunteer; maybe we should get some feedback from actual librarians.

**Comment by jspaaks** [comment]
> front the hyphen

neat

I think I prefer 
```
^[-0-9 ]{9,17}X?$
```
over the stricter one. It's perfectly fine if the regex is not as tightly defined as it could be, users are responsible for making sure their metadata is accurate, that's not something we should aim to do with mere schema validation. For example, whatever regex we choose, it would still be possible to mistype a number or have two numbers switch position. Similarly, whether the check digit is correct is not something we can check with only schema validation.

**Comment by jspaaks** [comment]
PR #335 was merged, closing this one
