### ISSUE TITLE
branching model revisited

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#324]
Spawned from https://github.com/citation-file-format/citation-file-format/issues/323#issuecomment-904477591

Perhaps there is value to changing to a different branching model like GitFlow.

For visitors, I think it would be convenient to have the default branch be the latest stable release (either a branch named `main` or `1.2.0`). That means that any development would need to happen elsewhere, maybe on branch `develop` or `1.3.0-alpha.0`. This would imply that PRs will by default be made against the wrong branch though (`main`/`1.2.0`) so that's something to be aware of.

**Comment by sdruskat** [comment]
Good point re the different perspectives. We coudl protect `main` and see if we as admins can change the branch that external PRs are put up against, as a safeguard against PRs put up against `main`? Could also include a checkbox in the PR template for this ("Please check if your PR is against the correct branch, `develop`).

**Comment by sdruskat** [comment]
Fixes in the schema guide and other documentation that aren't changes to the schema itself should still go against `main` though. I'll change the PR template to reflect that and create a `develop` branch, okay? 

Now we only have to create release branches to prepare new versions and we're almost back at GitFlow ;).
