### ISSUE TITLE
Deprecate `entity.orcid`

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#328]
I can actually see no case for an entity having an ORCID id, unless the entity hacks ORCID.
I believe that this is a bug, which should be fixed.

It *could* be replaced by [ROR](https://ror.org/) or [FundRef ID](https://www.crossref.org/services/funder-registry/), but perhaps websites are the best identifiers for orgs, and they're already possible to supply.

Doesn't need a "hotfix", as no one will use the key because there cannot be an entity ORCID.

**Comment by sdruskat** [comment]
@jspaaks I would consider *removing* `entity.orcid` for `1.3.0` as a bugfix similar to the changes in #462. And change the milestone to `1.3.0` as well.

I'm also in favour of supporting ROR instead as part of this work, as it has emerged as the community standard for identifying organizations over the last few years. See, e.g., https://ror.org/04bwf3e34 and https://ror.org/00rbjv475.

What do you think?

**Comment by jspaaks** [comment]
1. I'm OK with removing `orcid` from `entity` as a bugfix, especially because you mentioned one can't really get an ORCID account for a group, right?
2. spawned https://github.com/citation-file-format/citation-file-format/issues/480 to facilitate the discussion regarding RORs

**Comment by jspaaks** [comment]
FWIW `entity` has `ror` now, but also still has `orcid`. Should we remove it before releasing 1.3.0?

https://github.com/citation-file-format/citation-file-format/blob/8c594281f4fd687c0e29c8850132d5b1872861d2/schema.json#L346-L349

**Comment by sdruskat** [comment]
Closing as resolved in #522.
