### ISSUE TITLE
Create a creation service for CFF files

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#35]
Create a web service for the creation of CFF files from scratch.

This should include a web frontend where users can input their specs and create a file for download.

Should harvest available metadata from, e.g., ORCID and DOI providers or, indeed, integrate with providers' APIs to create a DOI in the process (needs to be investigated if, e.g., Zenodo supports this).

**Comment by jspaaks** [comment]
``cffinit`` is a first attempt at creation such a service: https://citation-file-format.github.io/cff-initializer-javascript/

**Comment by sdruskat** [comment]
I'll close this here now as `cffinit` is coming with update functionality.
