### ISSUE TITLE
Make the tools table more usable

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#350]
It's not nice to work with.

Ideas:

- Split libraries into their own section
- Rethink columns?
- Different presentation

**Comment by kevinmatthes** [comment]
The following idea extends the approach of a different representation.

How about outsourcing the table to a dedicated Markdown document with some brief explanations for each tool?  It could be considered a Tooling Catalogue, enriched with the tools the community developed.  Each tool might be presented in an own section with an overview about the most important information, just as the different CFF keys in `schema-guide.md`.

For instance, the section for the Ruby library might contain these basic information:

```
### `ruby-cff`

* written in: Ruby
* capabilities:
  * creation
  * editing / updating
  * validation
  * conversion
* abstract: ...
* additional information: ...
```

**Comment by kevinmatthes** [comment]
At the moment, the current representation has the option to introduce redundant entries.  The best example is `ruby-cff` which has multiple entries due to its ability to fulfill multiple tasks.  But also when one of the tools should be ported to another coding language, there would be basically two entries for the same tool.

The catalogue approach would help here to keep an overview.  If there should be multiple implementations of the same tool which have basically the same functionality, these could be listed in a subsection "Implementations".

**Comment by sdruskat** [comment]
Thanks, @kevinmatthes, I really like to idea. @jspaaks, can you see any reason why a dedicated tools doc wouldn't be a good idea?

**Comment by jspaaks** [comment]
I agree the tools table is really becoming unwieldy, so any attempt at improvement is worth considering. As to the proposed idea of a catalogue: I would like to point out that such a presentation answers a different kind of question than what the tools table attempted. Specifically, a catalogue view is able to answer questions like: "what tools are there in this landscape?" or even "what is Tool X?" whereas the tools table is able to answer questions like: "what tools can I use to convert from/to CFF?" and "Are there any validators available?". 

Having said that, I don't know if that shoudl stop us from trying out the catalogue view, so if @kevinmatthes wants to take a stab at that, that would be welcome AFAIC.

**Comment by kevinmatthes** [comment]
I am going to prepare an example based on `ruby-cff` in a new Pull Request.

**Comment by kevinmatthes** [comment]
I submitted my suggestion as #406.

**Comment by sdruskat** [comment]
> Having said that, I don't know if that should stop us from trying out the catalogue view, so if @kevinmatthes wants to take a stab at that, that would be welcome AFAIC.

I agree, let's try this until we can come up with something better (probably in the context of building the new website).
