### ISSUE TITLE
Julia package for CFF

### ISSUE THREAD

**Issue by mcmarius** [citation-file-format/citation-file-format#355]
Hello! I added support for CFF conversion from/to BibTeX in the Julia package [Bibliography.jl](https://github.com/Humans-of-Julia/Bibliography.jl) (since v0.2.16).

### Who needs the new tool?

Researchers or anyone working mainly within the Julia ecosystem.

### What should the new tool enable users to do?

For now, the tool enables conversion CFF <-> BibTeX in native Julia.

### What benefit would the new tool add?

Having a native Julia reader/converter will help with CFF adoption within communities using Julia.

### Implementation details

The implementation follows `cffconvert` and `ruby-cff`. Only CFF version 1.2.0 is implemented for now.

### Can you help?

- [x] Yes
- [ ] No

**Comment by sdruskat** [comment]
Looking at #357 now.
