### ISSUE TITLE
additional fields `subtitle` and `notices`

### ISSUE THREAD

**Issue by daniel-mohr** [citation-file-format/citation-file-format#360]
As we a trying to use Citation File Format for an automatic build process of writing documents in a repository system, we missed 2 fields:

* additional global field: `subtitle`
* additional field in `authors`: `notices`

In [our process](https://gitlab.hzdr.de/hmc/hmc-fair-data-commons/pandoc-latex-build-demonstration) we would use CITATION.cff to hold the metadata of the project and use it to generate the author information in a pdf document -- without storing it twice.

The field `subtitle` would be the subtitle of the document.

And `notices` would allow to define something like 'Thanks for funding by ABC'.

I think these fields are generally interesting for describing datasets. ?

Otherwise I would ask to allow additional fields in Citation File Format. ?

**Comment by sdruskat** [comment]
Hi @daniel-mohr and thank you for opening this issue. 
(I see we're fellow HMCers, I am leading the HERMES project in the 2020 cohort :slightly_smiling_face:.)

I'm afraid that what you are trying to do goes beyond the current scope of CFF, which is targeting exactly one use case, that of citation, and more precisely, software citation. Support for dataset citation is experimental, and we don't currently plan to develop it beyond basic support (i.e., reusing the available fields for dataset citation). 

I don't think that a `subtitle` field is something that will likely come into scope at all. We are planning to support different contribution roles (no ETA as of yet), to better support the trend of identifying these roles more precisely in publications (paper, software or other), but I'm unsure that this will meet your needs for a `notices` field. In the spirit of linking data, funding information for authors would be available via specifying the ORCID iD.

I'll close this issue as we will not at this time add these fields, but feel free to continue the discussion.
