### ISSUE TITLE
Emphasis in strings

### ISSUE THREAD

**Issue by ssstolk** [citation-file-format/citation-file-format#364]
Documentation on CFF currently does not address how one can emphasize part of a title. If it is possible, I propose a minimal example is added at the top or, for instance, under the _title_ property, where it is most likely to be needed.

Case in point:
I’ve recently added a CITATION.cff to one of my github repostiories (see [here](https://github.com/ssstolk/toe-lld/blob/master/CITATION.cff)). In the file, I have attempted to include a reference to a conference paper. That paper has a title that includes the name of a resource, which typically would be emphasized (using italics, most commonly) in the title, e.g.,
'_A Thesaurus of Old English_ as Linguistic Linked Data: Using OntoLex, SKOS and _lemon-tree_ to Bring Topical Thesauri to the Semantic Web ’. (The resources _A Thesaurus of Old English_ and _lemon-tree_ should be emphasized to contrast them with the rest of the title.)

In my CITATION.cff I have tried to get this result by adding asterisks (see line 24), but these get parsed as regular text. In bibtex a \emph tag is available, but I do not see anything of the sort mentioned in the CFF documentation. In short, how can one emphasize part of a title in a CITATION.cff? Is it even possible? Clear guides on this topic (and even where to look) have been difficult to locate, but perhaps I have overlooked something.

Thanks in advance for any help.

**Comment by sdruskat** [comment]
Hi @ssstolk and thanks for opening the issue.

There is a related issue (#269) where these (and other formatting issues) are discussed. I'd kindly ask you to contribute there, and close this issue as a duplicate.

Thanks!
