### ISSUE TITLE
specifying URLs/links

### ISSUE THREAD

**Issue by igordot** [citation-file-format/citation-file-format#369]
If you are including URLs in fields like `abstract` or `message`, should they be formatted in any way?

For example, would you just use `https://github.com` or should it be enclosed in angle brackets like `<https://github.com>`?

**Comment by sdruskat** [comment]
Hi @igordot and thanks for opening this issue.

The values of these fields are plain strings, they don't use Markdown or any other markup language. This means that you can format URLs as you see fit, or include them without formatting.

That being said, to keep the files as readable as possible, I wouldn't include any markup beyond angular brackets, or even leave URLs unmarked altogether...

Hope this helps.
