### ISSUE TITLE
[New Tool] cffreference:  Cite Existing CITATION.cffs in Yours

### ISSUE THREAD

**Issue by kevinmatthes** [citation-file-format/citation-file-format#376]
### Who needs the new tool?

Any people who would like to automate the citing of other projects by their `CITATION.cff`s.  Hence, it is also great for build routines.

### What should the new tool enable users to do?

People who would like to use `cffreference` can give it the path to an **existing, readable and valid** input `CITATION.cff` which will then be analysed regarding the lines to add to their own `CITATION.cff`.  If there is a `preferred-reference` configured, it will be used, by default.  If the output file is omitted, the results will be written to `stdout`, otherwise, the output will be appended to the given **readable and writable** output file (if it does not already exist, it will be created that way).

For instance, when having a local copy of *this* repository in order to provide the input file, one can cite it in the own repository using:

```
cffreference ../path/to/citation-file-format/CITATION.cff ../path/to/my-project/CITATION.cff
```

### What benefit would the new tool add?

Users will be able to automatically cite other projects in theirs.

### Implementation suggestions

My implementation suggestion can be found here:  https://github.com/kevinmatthes/cffreference.  It is written in Haskell (according to Haskell2010) and has a GNU Octave-based build routine.  The license is GPL 2.0.

It is just a draft (or "rapid prototype" in the terms of software engineering) but it sufficed to create a valid `CITATION.cff` for its own repository.

### Can you help?

- [x] Yes
- [ ] No

About an hour ago, I released version 0.2.

**Comment by kevinmatthes** [comment]
Version 0.4 fixes the citation of `preferred-citation` sections.  Furthermore, it applies the configured `type` of a preferred citation automatically and assumes the input file to be of `type: software`, by default.

**Comment by kevinmatthes** [comment]
Version 0.5 introduces two new placeholders to place in a `CITATION.cff`, at option:  `---` and `...`.  They are considered comments and will, hence, be skipped.

**Comment by sdruskat** [comment]
@kevinmatthes Thanks! As mentioned in #375, this is really helpful. Should we add it to the list of tools?

**Comment by kevinmatthes** [comment]
Yes, you are free to do so!

Please note that I am about to refactor the application in Rust, at the moment.  The original Haskell prototype still works, just the Rust version is not completely stable, yet.  When I finish the work on the Rust version, the Haskell prototype would become deprecated and is going to be replaced by the Rust executable in future releases.

I begun to refactor the prototype in Rust since it is easier to add command line option parsing in Rust than in Haskell.  In future releases, I plan to add some features using options, so the maintenance overhead would decrease.  Furthermore, the installation procedure is easier and the portability higher; the Haskell Platform appears to have different default content on multiple platforms what would disadvantage their users since they would need to install the respective missing libraries by hand using Cabal.

Anyway, you can add it as Haskell application since the Rust version is not finished, yet.  The Haskell version does not need any exotic libraries, so it is expected to work on multiple platforms.

**Comment by sdruskat** [comment]
Thanks @kevinmatthes! I've opened #384 to add this as a Haskell tool for now.
I'll let the PR auto-close this issue, but please reopen (or create a new one) when the Rust tool is implemented, and I'll make the necessary changes to the tools table then.

**Comment by kevinmatthes** [comment]
Okay, I will open a new issue, then. :+1:
