### ISSUE TITLE
Should the key "affiliation" in person objects accept a string or an entity object?

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#38]
As an affiliation will always be a named entity, future versions could have the key accept an entity object rather than a string.

**Comment by hainesr** [comment]
I thought exactly this as I was implementing [ruby-cff](https://github.com/citation-file-format/ruby-cff).

I had wondered whether the point was that the affiliation could be listed as an entity in the author list, and then mapped via it's name to the affiliation of the person. Not sure how one would validate that easily...

We certainly risk having the same entity as both an affiliation *and* an author, which is OK in code, but difficult to capture once serialized to yaml. And very difficult to de-serialize consistently.

**Comment by sdruskat** [comment]
As we're moving towards JSON Schema for the schema definition, we could technically make `affiliation` `string | #/definitions/entity`. I think the issue is that there is currently no way to _reference_ defined entities in CFF, while there is in YAML via anchors:

```yaml
foo: &anchor
bar: *anchor
```

I'd say that this anchor syntax isn't something that we should allow for CFF, just to keep things simple. In that respect, while allowing affiliations to be entities is technically possible (and perhaps even useful), there's no way to avoid duplications for, e.g., several authors that share the same affiliation ...

**Comment by sdruskat** [comment]
Closing as fixed in #523: Affiliations can now be one or more values of type `entity` or type `string` (including a mixture of both).
