### ISSUE TITLE
Including open-hardware

### ISSUE THREAD

**Issue by jcdupuis-ulaval** [citation-file-format/citation-file-format#381]
Great project :). Thanks for the great initiative.  We are contributing schematics and software for an open-hardware  project. Would it be possible to include 'hardware' in the type of contributions possible in the format ? I included it in my cff file but the word 'hardware' was automatically replaced with the word 'software' in the citation that was generated on GitHub. 

Thanks again :)

**Comment by sdruskat** [comment]
Thanks for this issue, @jcdupuis-ulaval!

There are two issues here:

1. Including `hardware` as a new type to be supported in the CFF schema. We would need to discuss whether adding a third type may soften the scope too much. Can you give us some example for metadata fields that are strictly necessary to support detailed hardware citation? Especially interested in those that aren't in the schema yet.
2. The rendering on GitHub is done via [`ruby-cff`](https://github.com/citation-file-format/ruby-cff/). I think it would not pick up the `type` value as it is invalid according to the [current schema](https://github.com/citation-file-format/citation-file-format/blob/main/schema.json), and instead revert back to the default, which is `software`. @hainesr may be able to confirm this or provide further explanation?

**Comment by jcdupuis-ulaval** [comment]
Thanks for the follow-up @sdruskat. Here is the link to the repository where we would like to use the type hardware : https://github.com/armercier/Open-seismic-electrical-design.git I think that the CERN was the first organization to start this movement. What is a bit complex from our end is that there is obviously software involved (e.g., firmware) but we would like others to be able to reproduce the physical hardware on which it runs. We are a University Lab and we do not have the scale to manufacture and distribute these through the University. In terms of metadata, I don't think that we need to add much. We may want to add the name of the microcontroller board but that's about it. Other compatible parts in the design can be swapped in and out according to the availability of parts. Firmware is written in C, C++ and the code for the user interface is written in Python. I expect that this would be quite common for most projects of this type. Thanks again for considering this enhancement.

**Comment by sdruskat** [comment]
Thanks, @jcdupuis-ulaval, for elaborating.

I have added this issue to be discussed when preparing the next version of the schema (ETA is currently unclear). This means  that the issue probably won't see much action before we get there, but will be picked up then. Hope that's okay?

**Comment by hainesr** [comment]
> The rendering on GitHub is done via [ruby-cff](https://github.com/citation-file-format/ruby-cff/). I think it would not pick up the type value as it is invalid according to the [current schema](https://github.com/citation-file-format/citation-file-format/blob/main/schema.json), and instead revert back to the default, which is software. @hainesr may be able to confirm this or provide further explanation?

Yes, this is correct, although I think it is perhaps only in the formatted output that `software` is substituted. I don't think that `hardware` would be changed just by loading the CFF file in. It would fail validation, of course, at the moment.

**Comment by jcdupuis-ulaval** [comment]
@sdruskat that's fine and thanks for considering this change. I think that it will enable quite a few exchanges and help student projects progress much faster :). Thanks also @hainesr for your comments. Have a good one everyone :)

**Comment by sdruskat** [comment]
@jcdupuis-ulaval, if you're generally interested in how hardware is treated in scholarly communications, etc., the "FAIR Principles for Research Hardware" RDA working group may be of interest to to: https://www.rd-alliance.org/groups/fair-principles-research-hardware. They run a virtual informative session this Thursday at the RDA Plenary: https://www.rd-alliance.org/plenaries/rda-19th-plenary-meeting-part-international-data-week-20%E2%80%9323-june-2022-seoul-south-korea-0.

**Comment by jcdupuis-ulaval** [comment]
@sdruskat  thanks for the links. Unfortunately, I will be in the plane coming back from another conference but I will see if I can get one of my graduate students to participate. It is something that I have wanted to do for a long time (i.e., I often find suboptimal experimental setups in papers because the authors did not have sufficient electrical engineering know-how to get a better setup) and now it seem as if we might have an appropriate method of providing this material. Thanks again for your help.

**Comment by danalvarez** [comment]
Hi all. Thanks for the interesting discussion. I am behind @jcdupuis-ulaval that having `hardware` as a new `reference-type` would be very useful. Planning on releasing several hardware designs in conjunction with the Aerospace Lab at my university and we would prefer if the citation was not rendered as `[Computer software]` by default. The hardware we're releasing contains the Altium design files and additional PDF schematics and fabrication files so that people can understand and replicate the design.
