### ISSUE TITLE
Stable version entry

### ISSUE THREAD

**Issue by z-a-f** [citation-file-format/citation-file-format#382]
It might be useful in some cases to have a `"stable_version"` (`"release_version"`) entry, alongside the `"version"`. The idea is that the `"version"` would track the latest, while the `"stable_version"` would track the latest release.

For example, [PyTorch](https://github.com/pytorch/pytorch) version from source is usually `1.<NEXT VERSION NUMBER>.0a`, while the latest version is `1.<CURRENT VERSION NUMBER>.<MINOR NUMBER>`

**Comment by sdruskat** [comment]
Thanks, @z-a-f, for this suggestion!

This could well be a valuable addition to the schema, especially as it would circumvent some of the semantic issues with versioning and what should be used and cited when, etc.

I'd like to hear @jspaaks' thoughts on this as well, but personally would consider adding it to the next release milestone.

**Comment by z-a-f** [comment]
@jspaaks Now that you put it that way, it makes sense. I think as long as there is a way to add some additional meta-data, it's totally find to use those.

@sdruskat I am going to close this to reduce noise, feel free to reopen.

**Comment by sdruskat** [comment]
> @z-a-f thanks for making the issue though, it's good to get different perspectives and collect ideas

D'accord!
