### ISSUE TITLE
orcid pattern is too loose

### ISSUE THREAD

**Issue by abelsiqueira** [citation-file-format/citation-file-format#392]
On cffinit, we found an issue with longer ids passing validation (https://github.com/citation-file-format/cff-initializer-javascript/issues/577). Apparently it's because the Orcid pattern is too loose:

https://github.com/citation-file-format/citation-file-format/blob/6c7e53846881c735e1db2cf686e9ed07dfa7fb8f/schema.json#L985

I think enclosing it in `^...$` should be enough to fix it.

**Comment by sdruskat** [comment]
Closing as fixed in #467.
