### ISSUE TITLE
[Bug] `bump2version` Configuration is Too Restrictive

### ISSUE THREAD

**Issue by kevinmatthes** [citation-file-format/citation-file-format#410]
`bump2version` not only allows the specification of the exact lines to update but also to update **all** occurrences of the current version number in a tracked file.

In my opinion, this feature would help especially to update the schema guide since it contains not only the current version number in the title but also in numerous examples.  Updating them by hand might require much effort.  It is easy to adjust `.bumpversion.cfg` such that all positions are updated at once.  One does not even need to know the lines or their actual content.  The adjustment simply requires the removal of the `search` and `replace` patterns from the respective entry.

I am going to raise a Pull Request with an appropriate fix.

**Comment by jspaaks** [comment]
I'm not sure I want to update version numbers in schema-guide.md automatically. While it's true that updating them by hand is quite some effort, I also think it's good to go over the full text of the guide and take a good look at each example to make sure everything is in order before making the release.

Just finding the current_version string and replacing it with a new string will be problematic, e.g. if current_version is 1.2.0 and identifiers has this example:

```yaml
identifiers:
  - description: "The versioned DOI for version 1.2.0 of the work."
    type: doi
    value: 10.5281/zenodo.3256192
```

Also, contrasting one `cff-version` behavior with another would become difficult.

Additionally, a minor problem that we had in the past is that bump2version would have trouble differentiating between `version` and `cff-version`. I can't remember why that happened, maybe that would have been fixable with a `^cff-version: 1.2.3$` type notation (but at the cost of missing other instances of the version string such as the one in the title and 2nd bullet point).

**Comment by kevinmatthes** [comment]
Thank you for your explanations, I now understand the current settings for bump2version.  I agree with you that the described scenario is indeed a problem as well as that reviewing the entire document and updating the respective occurrences manually is a good practice to ensure the documentation being ready for release, so I will close both this issue and #411.

By the way:  please be careful with relying on bump2version as it is not actively maintained, anymore; see https://github.com/c4urself/bump2version/issues/268.

**Comment by jspaaks** [comment]
>  bump2version as it is not actively maintained, anymore

Good to know, also for my other projects

**Comment by kevinmatthes** [comment]
@jspaaks

If you should already use Aeruginous which contains `cffreference`, you will also have access to a simple replacement for bump2version named `increment-version`.  It will update the given files like bump2version without any further settings, i.e. replacing every found occurrence of the specified version string, or, in case of a Rust project file, updating only the current package's version.  If you tell me your requirements, I can also add further logic to handle other configuration files.

The design is optimised for calling Aeruginous in GHA workflows to prepare everything for the next release, including an update of the main `date-released` field in any given CITATION.cff (i.e. the CLI implementation of my `cff-release-today` Action).
