### ISSUE TITLE
[Enhancement] Scriv for Asynchronous CHANGELOG Management

### ISSUE THREAD

**Issue by kevinmatthes** [citation-file-format/citation-file-format#412]
### Description

Large projects with both many branches and contributors often have difficulties with the management of their CHANGELOGs.  When submitting changes as Pull Requests, also updating the CHANGELOG is a good practice as the original authors know best how to summarise the changes introduced.

If there are numerous Pull Requests at once all making changes to the CHANGELOG, only the first Pull Request merged will not receive merge conflicts as then, the base branch will differ causing all further open Pull Requests to not be able to merge anymore.  The respective authors need to update with the base branch.  These updates are mandatory after each further Pull Request being merged.  This procedure is not only discouraging for the contributors but also slows down the development of the project since the CHANGELOG becomes a bottleneck.

With this issue, I would like to present a possible solution to this problem:  [Scriv](https://github.com/nedbat/scriv).  This Apache-2.0-licensed Python 3-CLI allows the CHANGELOG to be edited asynchronously by dividing the entries into fragments.  These fragments are stored centrally in one directory in the repository root to be appended by Scriv to the CHANGELOG on release.  An integration into existing workflows with [bump2version](https://github.com/c4urself/bump2version) is possible, as [this example](https://github.com/kevinmatthes/git-aliases-f18/blob/main/.justfile) shows (recipe `bump` in ll. 67).

With Scriv being set up for a repository, contributors can now also submit their CHANGELOG entries, at option.  This procedure also works with multiple branches such that for each branch, there will be a unique fragment in the central storage.  When merging to the base branches, the files will be added to the storage without causing merge conflicts and can be collected to the CHANGELOG on release.

Scriv works with both Markdown and reStructured Text CHANGELOGs, defaulting to the latter.  The preferences can be set in the following files:

* `changelog.d/scriv.ini`
* `setup.cfg`
* `tox.ini`

I would like to ask whether a setting up Scriv for this repository would benefit the maintenance and release workflows.  If you agree, I will submit a Pull Request with a suggestion on the initial setup.

### References

* Batchelder, N., McKee, K., Raj, A., & Serrão, R. G. (2022). Scriv (Version 0.17.0) [Computer software]. https://github.com/nedbat/scriv
* Matthes, K. (2022). git-aliases-f18 (Version 0.1.1) [Computer software]. https://github.com/kevinmatthes/git-aliases-f18
* Verkerk, C., & The bump2version Community. (2020). bump2version (Version 1.0.2-dev) [Computer software]. https://github.com/c4urself/bump2version

#### Note

Only the citation of git-aliases-f18 is the result of a permanently added CITATION.cff, the two other citations are taken from the corresponding Pull Requests and are, hence, previews which might change.

**Comment by kevinmatthes** [comment]
I do not use Scriv myself anymore, so I think this issue has become out of date.  If you are interested in such a solution anyway, I can configure you a similar approach using another software upon request.

**Comment by jspaaks** [comment]
Thanks Kevin! Sorry your PR got overtaken by events. The CHANGELOG clashes are a bit of a problem sometimes, but personally I'm not convinced that a tool like Scriv or one of its alternatives makes life easier (also considering contributors). It feels a bit like substituting one problem for another?

**Comment by kevinmatthes** [comment]
Well, this depends mostly on the configuration, especially regarding one particular alternative.

The original idea of Scriv is that the CHANGELOG should be assembled from pieces of information which cannot cause merge conflicts.  This goal is achieved by creating separate files, referred to as "fragments", for each piece of information and assigning it a file name consisting of an ISO 8601 timestamp, the Git user's name, as well as the current branch's name.  Into that file, Scriv will dump a form-like structure and leave the content provision to the user.  This manual effort together with the latest developments of Scriv I disagree with caused me to develop my own solution:  `comment-changes`, part of the Aeruginous Open Source Development Toolbox (thus, I will refer to this mode as Aeruginous, in the following, instead of `comment-changes`).

Aeruginous will harvest your Git commits to create you a fragment which follows the naming conventions of Scriv with a few more degrees of freedom and *already acutally contains* the changes to be put into the CHANGELOG.  Aeruginous therefore evaluates the commit messages as specified by the passed CLI options to check for the presence of a special separation pattern which divides the CHANGELOG category from one of its actual entries.  `Added ::= function "whatever"`, `Update README.md`, and `Removed ::= obsolete function "does_not_work"` can hence be collected automatically into a CHANGELOG fragment containing `function "whatever"` in the `Added` section as well as `obsolete function "does_not_work"` in the `Removed` section if the separator is set to `::=` to skip `Update README.md`.

Several projects already use this approach for automation applying the following concepts.

- Once a PR is created, the latest commit will be harvested into a CHANGELOG entry.  (One entry per PR.)
- Once PR is merged, its title is harvested into a CHANGELOG entry.  (One entry per PR.)
- Before merging a PR, the contributor invokes a GHA workflow to have Aeruginous harvesting all commits into CHANGELOG entries.  (Many entries per PR.)

The latest adjustments I am about to release soon will bring yet another option for automation:  have Aeruginous harvesting all commits *since the last release into a single fragment*.  This will be basically the entire CHANGELOG section for every noteworthy change; upon request, Aeruginous can also put this fragment into the right position, or it is pasted there manually by a maintainer / collaborator.

The last option would benefit especially contributors -- they do not even have to care about the CHANGELOG entries at all.  They just need to apply a certain commit message convention, i.e., commits will need to start with prefixes like the following *if* the respective changes shall be added to the CHANGELOG automatically.

- `Added <:>`
- `Changed <:>`
- `Deprecated <:>`
- `Fixed <:>`
- `Removed <:>`
- `Security <:>`

Minding a certain commit message convention is a small price to pay for contributors as many projects even embed checkers for their conventions into the CI steps.  For the maintainers and collaborators, the only effort would be to review the super-fragment before copying and pasting it into the correct position of the CHANGELOG; I assume that this should not take more than three minutes in total and, hence, considerably less time than resolving all merge conflicts due to CHANGELOG entry clashes.
