### ISSUE TITLE
[Enhancement] Call GitHub Action to Install Python 3 Dependencies

### ISSUE THREAD

**Issue by kevinmatthes** [citation-file-format/citation-file-format#418]
There is a GitHub Action named [`py-actions/py-dependency-install@v4`](https://github.com/py-actions/py-dependency-install) which will update `pip`, `setuptools`, and `wheel` prior to installing all dependencies listed in `requirements.txt` in a repository's root.  Thus, ll. 30—32 of `.github/workflows/testing.yml` could be reduced to the following line:

```yaml
      uses: py-actions/py-dependency-install@v4 # or full latest version with `...@v4.0.0`.
```

This is not only more readable, more convenient, and more comprehensive, these are also fewer lines to maintain.

If you agree, I can submit a Pull Request with exactly this change.

**Comment by jspaaks** [comment]
Hi Kevin,
thanks for making the suggestion. Personally, I would rather maintain a few lines that I instantly recognize compared to doing this via a third-party tool.

**Comment by kevinmatthes** [comment]
Okay, no problem!
