### ISSUE TITLE
Question: How to create a .cff with two suggestions?

### ISSUE THREAD

**Issue by olebole** [citation-file-format/citation-file-format#436]
Hi,

I am maintaining the legacy package [IRAF](https://iraf-community.github.io) and try to create a CFF file for it. The original text that came with the software is (see also the home page):

> There are two papers appropriate as references for IRAF in a publication:
>  * Tody, D., [The IRAF Data Reduction and Analysis System](https://iraf-community.github.io/doc/iraf.pdf), in Proc. SPIE Instrumentation in Astronomy VI, ed. D.L. Crawford, 627, 733 (1986) ([ADS:1986SPIE..627..733T](https://ui.adsabs.harvard.edu/abs/1986SPIE..627..733T))
>  *  Tody, D., [IRAF in the Nineties](https://iraf-community.github.io/doc/iraf92.pdf), in Astronomical Data Analysis Software and Systems II, A.S.P. Conference Ser., Vol 52, eds. R.J. Hanisch, R.J.V. Brissenden, & J. Barnes, 173 (1993) ([ADS:1993ASPC...52..173T](https://ui.adsabs.harvard.edu/abs/1993ASPC...52..173T))

Doug Tody wasn't the only author of the software; but a definitive list of authors is not available yet (only a self-compiled list based on some investigations) - the best author of the package as a whole is probably "IRAF authors" or so.

There is a repository (https://github.com/iraf-community/iraf) and an entry in the Astronomical Source Code Library (https://ascl.net/9911.002).  

How do I convert this to a CFF file? The automated tool seems not to know about multiple entries, and I also don't know how to distinguish between the author of the software and the author of the associated paper.

Can someone guide me?

**Comment by kevinmatthes** [comment]
I would like to suggest the following:

- add both papers as `references`
- set the latest paper as `preferred-citation`
- name the author of the papers as the main author of the software, i.e. in the first position in the list of authors
- add all known contributors as further authors, at option, using appropriate metadata
- add an anonymous group of people as further author in the last position

You mentioned that the software is based on the publications, so adding all known papers in the `references` section is an appropriate solution.  This allows for choosing one as `preferred-citation` while interested users can still choose to cite the work by another paper.  I would like to recommend to set the latest publication on the software as `preferred-citation` as it is newer; some researchers prefer to cite only the latest available resources and select their references *and* tools exclusively by this criterion.

Furthermore, you mentioned that the author of the papers also contributed to the software.  Thus, it is a good idea to name them as the main author.  All unknown contributors can be summarised as the software's community, just as you suggested.  It is now up to you whether or not to mention the other known contributors as they are technically already mentioned as members of the software's community.  As a reference, I recommend you the style of Clap, a Rust library for generating command line argument parsers:  https://github.com/clap-rs/clap/blob/master/CITATION.cff.

**Comment by olebole** [comment]
Thank you for the recommendations!

Using `references` seems however to be semantically not correct: the schema states that this field should contain 

> may include other […] not work describing the software or dataset.

which is what these references actually are. Following the intention of the original authors, IMO both should be `preferred-citation`, but this is syntactically impossible.

**Comment by kevinmatthes** [comment]
I see your point.  However, line 412 in schema-guide.md you are referring to starts the more verbose explanation with the following words.

> Similar to a list of references in a paper,

I experienced lists of references in papers to be often something like a list of further readings, as well.  When taking this into consideration, the best option would be make the 1986 paper the `preferred-citation` and the 1993 one a further reading; this suggestion is based on the titles of the publications as the 1986 paper sounds to me more like an introduction to the software than the 1993 one of which I assume that it is on the further development after the initial release.

**Comment by olebole** [comment]
Thank you! I created a PR for the .cff file in https://github.com/iraf-community/iraf/pull/306; could I ask you to have a short look?

There are a few things still unclear to me:

- in astronomy, almost all papers are catalogized on [ADS](https://ui.adsabs.harvard.edu/), and get a unique identified there which is the canonical way to refer to a paper (beside of the original page, if it exists). It would be worthwhile to include this in the reference. How would I do this?
- Is the URL of the rendered paper a "url" or a "repository-artefact"?
- For the software: What is the difference between "url" and "repository"?
- Many astronomy software is collected by the [Astronomical Source Code Library (ASCL)](https://ascl.net), including [IRAF](https://ascl.net/9911.002). From an example in the CFF schema, I would guess this is a "reference" with the URL as "repository", right? Is the type "catalogue" or "database" then (the example in the schema mentions "generic", but this seems wrong to me)?
- if one has only initials for an author, one would put them into "given-names", with dots, right?

**Comment by olebole** [comment]
Thank you for your help!
