### ISSUE TITLE
definitions.reference.pmcid should allow IDs with 8 digits

### ISSUE THREAD

**Issue by skafdasschaf** [citation-file-format/citation-file-format#443]
Currently, the CFF [schema](https://github.com/citation-file-format/citation-file-format/blob/develop/schema-guide.md#definitionsreferencepmcid) requires PMCIDs with seven digits ([example](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc10293285/)).
However, newly assigned IDs now have eight digits.
Thus, the regex used for validating this field should be `^PMC[0-9]{7,8}$`

**Comment by sdruskat** [comment]
Thanks, @skafdasschaf, for notifying us of this. Should definitely laxen the schema regarding this in the next minor release!

**Comment by jspaaks** [comment]
Fixed by PR #469, closing this issue
