### ISSUE TITLE
Review validation of examples

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#445]
The tests that are being performed assume cffconvert 1.x, I think we can simplify the testing by using cffconvert 2.x

https://github.com/citation-file-format/citation-file-format/tree/1.2.0/examples/validate.py#L1-L23

Probably the simplification will replace 

- examples/validator.py
- examples/validate.py
- examples/helpers/load_cff.py

with one new file

**Comment by sdruskat** [comment]
Sounds good, happy for you to go ahead and try it :).

**Comment by jspaaks** [comment]
I created PR #507 which changes the philosophy of the testing a bit. If that PR is merged, this repo 

- will no longer use `cffconvert` but instead uses `jsonschema` directly for its validation
- will no longer do testing of previously released versions of CFF, just the bleeding edge. Sidenote: `cffconvert` will continue to do multiversion testing, because there it's necessary to make sure cffconvert can correctly ingest from historic versions;
- will be internally consistent--every file will be about the same version of CFF

**Comment by jspaaks** [comment]
The relevant PR #507 was merged, closing this issue
