### ISSUE TITLE
[Suggestion] Enhance Integration with GitHub Linguist

### ISSUE THREAD

**Issue by kevinmatthes** [citation-file-format/citation-file-format#448]
When editing code with GitHub's web editor, the highlighting is done with a Ruby library named Linguist; see https://github.com/github-linguist/linguist.  The library is also responsible for the coding language recognition whose result is shown on a project's landing page as a statistic at which ratio a certain language is used within the repository.

The languages known to Linguist are configured in https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml.  It is also possible to create an alias for a particular language, e.g. V is defined to be 80% like Go such that it is basically handled as Go; see https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml#L7187-L7198.

I would like to suggest to also register CFF to the list of known languages as it is already accepted by GitHub as its default format for repository citation metadata.  The redirection should be obviously to YAML as CFF builds upon YAML 1.2, for the colour I would like to suggest #2A7FFF which is the background colour of this organisation's icon.  The Linguist detection should recognise files ending in `.cff` in general as well as files named `CITATION.cff` in particular.

What do you think about this possibility as well as the suggested setup?

**Comment by kevinmatthes** [comment]
I am sorry, I was mistaken as CFF is already supported in the YAML category; maybe an entry for CFF as a language on its own might be too much ... ?

**Comment by kevinmatthes** [comment]
I assume that this issue is of rather low priority, so I am going to close it.

**Comment by jspaaks** [comment]
Hi @kevinmatthes,

sorry we are often so slow to respond, it's difficult to find the time sometimes. Anyway I'd like to keep this issue open as an idea even if we're not immediately working on it.
