### ISSUE TITLE
Consider updating the license enum

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#454]
Relevant part of the schema:

https://github.com/citation-file-format/citation-file-format/blob/396f738fb025b1d8acdb02a56ffc923f95dc8999/schema.json#L516-L981

I set up a tool to make it easy, haven't tested in a while though :)

https://github.com/citation-file-format/get-spdx-licenses

Related:
- #450

**Comment by jspaaks** [comment]
BTW I went ahead and added these changes to the preliminary copy of the 1.3 schema that is bundled with `cffconvert`

**Comment by jspaaks** [comment]
Also made a PR here, #461.

**Comment by sdruskat** [comment]
Closing as fixed in #461.
