### ISSUE TITLE
Status list incomplete?

### ISSUE THREAD

**Issue by hainesr** [citation-file-format/citation-file-format#47]
In the [status list](https://citation-file-format.github.io/1.0.3/specifications/#/status-strings) for a publication, are we missing a "published", "complete" or "finished" status?

**Comment by sdruskat** [comment]
Hm, I wouldn't think so, as "published", etc. would be the default status, no?

**Comment by hainesr** [comment]
Ah, so one would leave it blank if published. That's fine then.

**Comment by sdruskat** [comment]
Yep, would just be left out if the reference is "properly published".
