### ISSUE TITLE
Update `bump2version` requirement or remove

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#473]
While reviewing #470, I stumbled over the instance of `1.2.0` in `.bumpversion.cfg` and found that the project is [no longer supported](https://github.com/c4urself/bump2version#readme).

We should consider updating to the maintained [bump-my-version](https://github.com/callowayproject/bump-my-version), or discuss another way of bumping versions.

**Comment by jspaaks** [comment]
I'd be OK with removing, mostly because I don't trust the tool to do exactly what I want, so I have to go over its changes anyway. Seeing as our last release is 2 years ago, I think this is acceptable to do by hand.

**Comment by jspaaks** [comment]
Created PR https://github.com/citation-file-format/citation-file-format/pull/481

**Comment by sdruskat** [comment]
Closing as fixed in #481.
