### ISSUE TITLE
How to give an entity author an affiliation?

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#479]
When your `CITATION.cff` uses `name` to collectively attribute the work to a team, the team's affiliation cannot be written down in CFF 1.2.0

**Comment by sdruskat** [comment]
Nice catch @jspaaks!

One "hack" would be to suggest using `person.alias` to provide the name of the team and make use of `person.affilliation`.

Alternatively, we could give `entity` an affiliation as well?

**Comment by jspaaks** [comment]
> Alternatively, we could give entity an affiliation as well?

That would be my preferred approach

**Comment by jspaaks** [comment]
Made PR https://github.com/citation-file-format/citation-file-format/pull/485 just in case

**Comment by jspaaks** [comment]
PR #485 was merged, closing
