### ISSUE TITLE
In the spec, reference/issue-date is listed as type String.

### ISSUE THREAD

**Issue by hainesr** [citation-file-format/citation-file-format#48]
Should be Date for consistency.

**Comment by sdruskat** [comment]
I have left this as string to allow for non-standard issue dates such as in `Journal of Something 42(6) (November-December)`, where `issue: 12` and `issue-date: November-December`.

Might be a matter of me having worked for a large publishing house for too long, but unfortunately these formats exist. 

If we agree that this shouldn't be valid input, it should be changed indeed. What do you think?

**Comment by hainesr** [comment]
Right, I see the rationale behind this now.

How is it best to do a pull request on the schema docs? I think an explanation would help others and I'm happy to do this.

**Comment by sdruskat** [comment]
Cheers Rob, if by "schema docs" you mean the specs themselves, just push a PR against https://github.com/citation-file-format/citation-file-format.github.io. As I think this would only add an explanation I don't think we'd need to release another version for this.
