### ISSUE TITLE
Consider adding ROR as identifier for entities

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#480]
Spawned from https://github.com/citation-file-format/citation-file-format/issues/328#issuecomment-1772582570. Examples:

- https://ror.org/04bwf3e34 (DLR)
- https://ror.org/00rbjv475 (Netherlands eScience Center)

**Comment by jspaaks** [comment]
As to how to approach this: under entity, add `ror` as key that can take the identifier.

```yaml
authors:
- name: the authors
  ror: 04bwf3e34
```

Need to look into this but maybe ~~`[a-z0-9]{9}`~~`0[a-z0-9]{8}`?

See https://github.com/ror-community/ror-schema/blob/a985c6e97293c0ebcc50aae89a2092c557c1dbec/ror_schema_v2_0.json#L116

**Comment by jspaaks** [comment]
Made PR #484

**Comment by sdruskat** [comment]
Closing as fixed in #484.
