### ISSUE TITLE
Support "type" values other than "software" and "dataset"

### ISSUE THREAD

**Issue by MattF-NSIDC** [citation-file-format/citation-file-format#498]
Reading the schema guide, [`type` is documented as only supporting values `software` and `dataset`](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#type).

I have been using Quarto to create technical blogs, documentation sites, and slide decks. I manage them on GitHub, then use the GitHub-Zenodo integration to DOI, for example a `presentation`. For now, I'm manually editing my Zenodo records to change their type to `presentation`, but I'd like that to be allowed by the CFF spec too!

**Comment by kevinmatthes** [comment]
For my projects, I usually create a `preferred-citation` with the corresponding `type` whenever `software` and `dataset` are not sufficient.  Maybe this might be an option for your use case, as well?

I remember a similar issue where a user requested further types for the top-level `type` field.  During the discussion, it was argued that the main reason why there are no further values allowed would be that CFF would be mostly designed for working with software-like entities, i.e. `software` and `dataset`s.

Maybe this request will be taken into account for future releases but until then, I guess that the workaround from above might be the solution.

**Comment by MattF-NSIDC** [comment]
My apologies, I must not have searched very thoroughly my first time. I found this issue: https://github.com/citation-file-format/citation-file-format/issues/430

and it sounds like this is a fairly active discussion, albeit in a closed issue. I'll close this issue now.
