### ISSUE TITLE
Look into Zotero support

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#50]
It'd be great if Zotero supported CFF in that you could harvest the CFF metadata from a repository website (GitHub, GitLab, Bitbucket, etc.) via the "Save to Zotero" browser add-on (https://github.com/zotero/zotero-connectors/)!

**Comment by jspaaks** [comment]
May be possible if we're willing to use a cff retrieval service, for example using cffconvert like so:
https://us-central1-cffconvert.cloudfunctions.net/cffconvert?url=https://github.com/citation-file-format/cff-converter-python&outputformat=cff

If we'd go that route, maybe we should look into adding an export to ``cffconvert`` that produces a format that zotero can already ingest.

**Comment by sdruskat** [comment]
This is now partly ([for GitHub](https://github.com/zotero/translators/pull/2592)) solved as Zotero supports CITATION.cff input.
