### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by dschwoerer** [citation-file-format/citation-file-format#51]
Stupid question: Where is the documentation on how it looks like, and maybe some examples?

I came to this site:
https://citation-file-format.github.io/
Which motivates me to use it - but does not feature examples as far as I could tell.

Then I went to github:
https://github.com/citation-file-format 
It seems to have been the only link that might contain the documentation.

That contains among some language specific things (which I am currently not interested in, as I am still trying to rather understand what it is) and the websites only to repositories:
* https://github.com/citation-file-format/schema
Which only contains (?) tests to make sure a file is valid CFF (again, don't want that yet)

* https://github.com/citation-file-format/citation-file-format
Which contains one example file (:tada:) but in an old version and only one (rather simple) entry.

What have I missed? Where can I learn what a file looks like, except for reading the python parser in schema?

**Comment by sdruskat** [comment]
Hi @dschwoerer,

Thanks for your interest, not a stupid question at all! In fact, this seems to hint that the documentation/website should be made more accessible.

You can find examples in the specifications themselves (https://citation-file-format.github.io/1.0.3/specifications/#/examples), but I'll also put some on the homepage as soon as I have the time.

If you want to see a feature-complete example, you can have a look at https://github.com/citation-file-format/schema/blob/master/CFF-Core/CITATION.cff. (WARNING: Everything that's possible is in there, so may be too much for a start).

Additionally, if you have a Zenodo DOI for your software handy, you could automatically create a `CITATION.cff` file via this project: https://github.com/3D-e-Chem/release2cff.

Let me know if you have any further questions.

**Comment by dschwoerer** [comment]
Thanks :+1:
