### ISSUE TITLE
Why was CFF invented ?

### ISSUE THREAD

**Issue by Malix-Labs** [citation-file-format/citation-file-format#540]
Hello !

Why was CFF when [BibTeX](https://www.bibtex.org/) already exists ?

[BibTeX](https://www.bibtex.org/) seems easier to parse than CFF (which itelsef is a YAMLoïd)

Was its syntax too unappealing ?
Was it too tied to the LaTeX ecosystem ?
Something else ?

I don't see anything in https://github.com/citation-file-format/citation-file-format.github.io and would have liked to see it

**Comment by sdruskat** [comment]
Hi @Malix-Labs, and thanks for asking this.

This is a question we've heard a number of times. We're currently working on a new website that will include a section on history of CFF as well as an FAQ section, where this question will be answered. This will still take some time to finish.

In short: A bit of all of the things you hint at, and some other reasons. Specifically, BibTeX is not good at providing (or enforcing) the metadata that is needed for software citation according to the [software citation principles](https://peerj.com/articles/cs-86/). I.e., `@software` in BibTeX is an alias for `@misc` and[ not its own type](https://www.bibtex.com/e/entry-types/) with type-specific fields, whereas CFF provides exactly that (e.g., different types of repository URLs, version, etc.).
