### ISSUE TITLE
Fair to say that CFF covers offer to import of metadata?

### ISSUE THREAD

**Issue by katrinleinweber** [citation-file-format/citation-file-format#58]
Hello,

I'm trying to visualise the "coverage" of CFF and codemeta.json in the publishing workflow.
Is it fair to say that CFF can cover:

1. developer provides basic citation metadata
1. user finds metadata
1. user imports metadata into reference manager

?

From the [Tools section](https://github.com/citation-file-format/citation-file-format#tools) I gather that the last step might need a converter. [For codemeta, only 1. & 2. seem to be available so far](https://codemeta.github.io/tools/).

The final step would of course be "use cites the item in a document and renders the citation". There is no CFF tool for that yet, is there?

Thanks for any comments, and kind regards :-)

**Comment by sdruskat** [comment]
Hi Katrin,

Thanks. Yes, 1. and 2. are covered.
Implementing 3. *directly* (e.g., for Zotero) is future work still, hope to be able to make some progress during the [RSE18 Hack Day](https://citation-file-format.github.io/events/rse18-hack-day/) (will you be there?). There is, however, https://github.com/citation-file-format/cff-converter-python which can convert to BibTeX and EndNote (among others), so yes, conversion is needed.

I guess for  "use[r] cites the item in a document and renders the citation", BibTeX conversion counts towards that, but not entirely.

Hope this helps, let me know if you need any further comments?

**Comment by katrinleinweber** [comment]
Thanks for clarifying the points :-)

I'll not be at RSE18, but on holiday. 

> [...] let me know if you need any further comments?

Well, I added one to https://figshare.com/articles/Track_2_Lightning_Talk_Should_CITATION_files_be_standardized_/3827058 a while ago ;-)

**Comment by sdruskat** [comment]
Closing this, as it's stale, and the basic workflow is implemented for some widely used tools, e.g.

1. Dev provides basic citation metadata.
2. User finds metadata
3. User imports metadata into reference manager (from CFF file found anywhere into JabRef, or automagically from GitHub via Zotero browser plugin)
4. User uses metadata to cite software and renders in doc (e.g., using BibTeX from GitHub, or exported from Zotero/JabRef).
