### ISSUE TITLE
Generating the schema's license enum automatically

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#59]
should we maybe make a script that generates the license enum for usage in the schema (e.g. here https://github.com/citation-file-format/schema/blob/66951a4c5251f5ba00a4364e9d0f1cbb67afa11f/CFF-Core/schema.yaml#L73) from the spdx list of licenses?
https://github.com/spdx/license-list-XML/tree/master/src

**Comment by sdruskat** [comment]
Thanks for filing this. Sounds like a great idea! I'm back from my holidays at the beginning of Aug and will look into then.

**Comment by jspaaks** [comment]
I created a tool that can do more or less this: https://github.com/jspaaks/get-spdx-licenses

**Comment by sdruskat** [comment]
Closing this, as we now have https://github.com/citation-file-format/get-spdx-licenses.
