### ISSUE TITLE
Merge the schema and .github.io repositories for v1.1.0

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#71]
This will help streamline the release process and will support a better understanding of what CFF *is*, i.e., what is being talked about when talking about CFF (the schema vs. the specs vs. the website vs. the concept, etc.).

- [x] Vet options (merge into .github.io vs. merge into this repository)
- [x] Merge
- [x] Streamline releases with CI support

**Comment by jspaaks** [comment]
OK, crazy plan below

what do you think about creating a ``cff-events`` and a ``cff-tooling`` in addition to the already existing ``citation-file-format``? This would help declutter the repos. We could transfer existing repos as follows:

- ``citation-file-format``
    - should contain the result of some kind of merge of what is now
        1. ``citation-file-format`` (this would then become the only repo in the github organization, if we go ahead with the changes below)
            - ``schema.yaml`` (what is now ``schema/CFF-Core/schema.yaml``)
            - ``README.md`` (we should add a section to the readme that describes steps on how to make a new release)
            - (only add files here that we want to be part of a release on Zenodo 
              via GitHub-Zenodo automatic integration; this also means moving
              away from the model where the repo includes old versions of the
              specs, not sure at this point what the full implications of such a move
              will be/whether there are important downsides)
            - some sort of 'guide to reading the schema'. probably similar content-wise
              to the pdfs (e.g. https://citation-file-format.github.io/assets/pdf/cff-specifications-1.0.3.pdf).
              Not sure what format is best suited for this, both as a source and as target format
              (maybe markdown as source and pdf as target? Does that mean commiting the pdfs to git?)
        1. ``schema``
        1. ``citation-file-format.github.io``
- ``cff-tooling`` (to be created)
    - ``cff-converter-python``
    - ``doi2cff``
    - ``cff-initializer-javascript``
    - ``github2cff``
    - ``soccs``
    - ``ruby-cff``
    - ``cff-reader-java``
- ``cff-events`` (to be created)
    - ``rse-18-hackday``
    - ``cw19``
    - ``future-event-1``
    - ``future-event-n-1``
    - ``future-event-n``

Couple more remarks:

- Perhaps irrelevant if we decide to merge repos, but I would be in favor of ditching the ``master`` + ``src`` dual branch setup in ``citation-file-format.github.io``. 
- I would be in favor of having a ``/docs`` on ``master`` branch instead of a ``gh-pages`` branch in ``citation-file-format``
- Also, if we can avoid Travis pushing pdfs to the internets, I'd be in favor of that (might not be attainable if we want to generate pdfs, we'll see).

**Comment by jspaaks** [comment]
If we decide to merge repos, this link may come in handy https://stackoverflow.com/questions/1683531/how-to-import-existing-git-repository-into-another#answer-1684694 if we want to retain git history. I've used it for merging the 7 or so repositories that we used to have in https://github.com/research-software-directory/research-software-directory into 1 monorepo; there it worked except for the occasional glitch (in GitHub, not git).

After merging we should then proceed to enable GitHub-Zenodo integration, and make a release as-is (maybe call it ``1.1.0-alpha``) before commencing to remove/update stuff.

**Comment by jspaaks** [comment]
I made a draft PR https://github.com/citation-file-format/citation-file-format/pull/77 to see what merging would involve. First impression is it looks like it could make our lives simpler. Let me know what you think @sdruskat

**Comment by sdruskat** [comment]
Documenting this: We've decided to merge schema into c-f-f (done with #77 merge), and keep the .github.io repo for a simpler landing page (#76).

**Comment by sdruskat** [comment]
Leaving this open for a postponed decision on whether to have separate orgs for events and tooling.

**Comment by jspaaks** [comment]
Good with me. Note we have https://github.com/cff-events if we want (just sent @sdruskat an invite).

**Comment by sdruskat** [comment]
Created the cff-tooling org as well. We can always decide to ditch it, but I do feel it'll add better structure to the whole project. Invited @jspaaks as well.

Closing this.
