### ISSUE TITLE
Rename 'citation-file-format.github.io' repo to something simpler like 'website'

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#78]
@jspaaks: I don't think that this is actually possible. From the [GH Pages docs](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages):

```
If your site is a User or Organization Page that has a repository named <username>.github.io or <orgname>.github.io, you cannot publish your site's source files from different locations. User and Organization Pages that have this type of repository name are only published from the master branch.
```

There is no mechanism to publish an org site if there is no repo of that name, so we will just have to overwrite c-f-f.github.io once we have moved content to the main repo.

**Comment by jspaaks** [comment]
OK, well in a way that makes things easier, right? Not possible means we don't have to figure out how to make it work :)
