### ISSUE TITLE
Switch off Travis for everything but PRs + lock down master in new main repo to only allow contributions via PR

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#81]

**Comment by sdruskat** [comment]
@jspaaks We got rid of Travis in favour of GH Actions, should we still protect `main`? I don't see why we shouldn't, if we relax our (non-existing) review-before-merge rules a bit. Or adopt [unreviewed code triage](https://hexatomic.github.io/unreviewed-code-triage.html).

I guess we should formalize an actual development process at some point...

**Comment by sdruskat** [comment]
Superseded by #169, closing.
