### ISSUE TITLE
Making releases (1.0.3-4 and 1.1.0)

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#82]
preliminary plan is
- [x] make a new release ``1.0.3-4`` of ``citation-file-format/citation-file-format.github.io`` using the old release mechanism. This way, we'll have a snapshot of the complete repository, including old specifications
- [x] merging #77 will update ``citation-file-format/citation-file-format``
    - [x] (optional) clean up #77's README
    - [x] (optional) add tests
- [x] enable GitHub-Zenodo integration on ``citation-file-format/citation-file-format``
- [x] use GitHub-Zenodo integration to make a release of the ``citation-file-format/citation-file-format`` repo's ``master`` branch (i think we said ``1.1.0``?)
    - Note that previous releases will not be part of the history of releases you see on Zenodo, because they are of different repositories. But that's OK, we can link previous versions manually if we think that's important.
    - Also note that ``citation-file-format/citation-file-format`` will abandon the ``x.y.z-n`` versioning in favor of just ``x.y.z``.

**Comment by sdruskat** [comment]
Released [1.0.3-4](https://github.com/citation-file-format/citation-file-format.github.io/releases/tag/1.0.3-4).

**Comment by sdruskat** [comment]
>       * Note that previous releases will not be part of the history of releases you see on Zenodo, because they are of different repositories. But that's OK, we can link previous versions manually if we think that's important.

1.1.0 has been released manually on Zenodo now, we need to fix the integration ideally to swap out source repos.
Meanwhile the above note has proven correct, as a new content DOI has been generated.
Nevertheless, this can be closed.
