### ISSUE TITLE
Recording article page numbers

### ISSUE THREAD

**Issue by sbliven** [citation-file-format/citation-file-format#88]
I'm a little confused by the meaning of the references.pages field in CFF. The spec defines this as 'The number of pages of the work' and requires an Integer. For articles, it is important to specify page numbers for the article. This requires ranges (e.g. `10--20` in bibtex) and need not be numeric (e.g. one of my papers is `e1006791`). How should these be specified in CFF? Should the `section:` key be used instead of `pages:`?

**Comment by jspaaks** [comment]
Looking at the documentation, https://zenodo.org/record/1405679#.XV0DgfxS9tc, I think this key was meant to record the total number of pages of e.g. a book. I believe sometimes you see that denoted in references as ``pp``.  

I'd say you are looking for the ``start`` and ``end`` keys. See table 3 on page 7 of the url above.

**Comment by sdruskat** [comment]
> I'd say you are looking for the `start` and `end` keys. See table 3 on page 7 of the url above.

Correct.

**Comment by sbliven** [comment]
Thanks for clarifying!

Maybe it would be worth including this in the 'article' reference example. The current example is from peerJ, which unusually doesn't use page numbers, so it was hard to find the start and end keys.
